// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: registration/registration.proto

package registration

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 预约挂号请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     int64                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`    // 患者ID
	ScheduleId    int64                  `protobuf:"varint,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"` // 排班ID
	CardType      string                 `protobuf:"bytes,3,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`        // 挂号类型（普通/专家/急诊）
	VisitDate     string                 `protobuf:"bytes,4,opt,name=visit_date,json=visitDate,proto3" json:"visit_date,omitempty"`     // 就诊日期（yyyy-MM-dd）
	Complaint     string                 `protobuf:"bytes,5,opt,name=complaint,proto3" json:"complaint,omitempty"`                      // 主诉
	DoctorId      int64                  `protobuf:"varint,6,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`       // 期望医生ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_registration_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *RegisterRequest) GetScheduleId() int64 {
	if x != nil {
		return x.ScheduleId
	}
	return 0
}

func (x *RegisterRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *RegisterRequest) GetVisitDate() string {
	if x != nil {
		return x.VisitDate
	}
	return ""
}

func (x *RegisterRequest) GetComplaint() string {
	if x != nil {
		return x.Complaint
	}
	return ""
}

func (x *RegisterRequest) GetDoctorId() int64 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

// 预约挂号响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId int64                  `protobuf:"varint,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"` // 预约ID
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`     // 挂号序号
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                     // 状态
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`              // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_registration_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAppointmentId() int64 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

func (x *RegisterResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *RegisterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 查询号源请求
type GetSchedulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  int64                  `protobuf:"varint,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"` // 科室ID
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`                                      // 日期（yyyy-MM-dd）
	CardType      string                 `protobuf:"bytes,3,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`              // 挂号类型
	DoctorId      int64                  `protobuf:"varint,4,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`             // 医生ID（可选）
	Page          *common.PageRequest    `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`                                      // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchedulesRequest) Reset() {
	*x = GetSchedulesRequest{}
	mi := &file_registration_registration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchedulesRequest) ProtoMessage() {}

func (x *GetSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchedulesRequest.ProtoReflect.Descriptor instead.
func (*GetSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{2}
}

func (x *GetSchedulesRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *GetSchedulesRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetSchedulesRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *GetSchedulesRequest) GetDoctorId() int64 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *GetSchedulesRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// 号源信息
type ScheduleInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId     int64                  `protobuf:"varint,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`            // 排班ID
	DoctorId       int64                  `protobuf:"varint,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`                  // 医生ID
	DoctorName     string                 `protobuf:"bytes,3,opt,name=doctor_name,json=doctorName,proto3" json:"doctor_name,omitempty"`             // 医生姓名
	DepartmentName string                 `protobuf:"bytes,4,opt,name=department_name,json=departmentName,proto3" json:"department_name,omitempty"` // 科室名称
	Date           string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`                                           // 日期
	TimeSlot       string                 `protobuf:"bytes,6,opt,name=time_slot,json=timeSlot,proto3" json:"time_slot,omitempty"`                   // 时段
	CardType       string                 `protobuf:"bytes,7,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`                   // 号别
	TotalCount     int32                  `protobuf:"varint,8,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`            // 总号数
	RemainCount    int32                  `protobuf:"varint,9,opt,name=remain_count,json=remainCount,proto3" json:"remain_count,omitempty"`         // 剩余号数
	Fee            float64                `protobuf:"fixed64,10,opt,name=fee,proto3" json:"fee,omitempty"`                                          // 挂号费
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduleInfo) Reset() {
	*x = ScheduleInfo{}
	mi := &file_registration_registration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleInfo) ProtoMessage() {}

func (x *ScheduleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleInfo.ProtoReflect.Descriptor instead.
func (*ScheduleInfo) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{3}
}

func (x *ScheduleInfo) GetScheduleId() int64 {
	if x != nil {
		return x.ScheduleId
	}
	return 0
}

func (x *ScheduleInfo) GetDoctorId() int64 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *ScheduleInfo) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *ScheduleInfo) GetDepartmentName() string {
	if x != nil {
		return x.DepartmentName
	}
	return ""
}

func (x *ScheduleInfo) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ScheduleInfo) GetTimeSlot() string {
	if x != nil {
		return x.TimeSlot
	}
	return ""
}

func (x *ScheduleInfo) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *ScheduleInfo) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ScheduleInfo) GetRemainCount() int32 {
	if x != nil {
		return x.RemainCount
	}
	return 0
}

func (x *ScheduleInfo) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

// 查询号源响应
type GetSchedulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*ScheduleInfo        `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"` // 号源列表
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`           // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchedulesResponse) Reset() {
	*x = GetSchedulesResponse{}
	mi := &file_registration_registration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchedulesResponse) ProtoMessage() {}

func (x *GetSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchedulesResponse.ProtoReflect.Descriptor instead.
func (*GetSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{4}
}

func (x *GetSchedulesResponse) GetSchedules() []*ScheduleInfo {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *GetSchedulesResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_registration_registration_proto protoreflect.FileDescriptor

const file_registration_registration_proto_rawDesc = "" +
	"\n" +
	"\x1fregistration/registration.proto\x12\fregistration\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xc8\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x03R\tpatientId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\x03R\n" +
	"scheduleId\x12\x1b\n" +
	"\tcard_type\x18\x03 \x01(\tR\bcardType\x12\x1d\n" +
	"\n" +
	"visit_date\x18\x04 \x01(\tR\tvisitDate\x12\x1c\n" +
	"\tcomplaint\x18\x05 \x01(\tR\tcomplaint\x12\x1b\n" +
	"\tdoctor_id\x18\x06 \x01(\x03R\bdoctorId\"\xb1\x01\n" +
	"\x10RegisterResponse\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\x03R\rappointmentId\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb1\x01\n" +
	"\x13GetSchedulesRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\x03R\fdepartmentId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1b\n" +
	"\tcard_type\x18\x03 \x01(\tR\bcardType\x12\x1b\n" +
	"\tdoctor_id\x18\x04 \x01(\x03R\bdoctorId\x12'\n" +
	"\x04page\x18\x05 \x01(\v2\x13.common.PageRequestR\x04page\"\xba\x02\n" +
	"\fScheduleInfo\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\x03R\n" +
	"scheduleId\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\x03R\bdoctorId\x12\x1f\n" +
	"\vdoctor_name\x18\x03 \x01(\tR\n" +
	"doctorName\x12'\n" +
	"\x0fdepartment_name\x18\x04 \x01(\tR\x0edepartmentName\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x1b\n" +
	"\ttime_slot\x18\x06 \x01(\tR\btimeSlot\x12\x1b\n" +
	"\tcard_type\x18\a \x01(\tR\bcardType\x12\x1f\n" +
	"\vtotal_count\x18\b \x01(\x05R\n" +
	"totalCount\x12!\n" +
	"\fremain_count\x18\t \x01(\x05R\vremainCount\x12\x10\n" +
	"\x03fee\x18\n" +
	" \x01(\x01R\x03fee\"z\n" +
	"\x14GetSchedulesResponse\x128\n" +
	"\tschedules\x18\x01 \x03(\v2\x1a.registration.ScheduleInfoR\tschedules\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.common.PageResponseR\x04page2\xc2\x01\n" +
	"\x13RegistrationService\x12T\n" +
	"\x13RegisterAppointment\x12\x1d.registration.RegisterRequest\x1a\x1e.registration.RegisterResponse\x12U\n" +
	"\fGetSchedules\x12!.registration.GetSchedulesRequest\x1a\".registration.GetSchedulesResponseBO\n" +
	"\x1ecom.hismixed.grpc.registrationZ-github.com/his-mixed/go/pkg/grpc/registrationb\x06proto3"

var (
	file_registration_registration_proto_rawDescOnce sync.Once
	file_registration_registration_proto_rawDescData []byte
)

func file_registration_registration_proto_rawDescGZIP() []byte {
	file_registration_registration_proto_rawDescOnce.Do(func() {
		file_registration_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registration_registration_proto_rawDesc), len(file_registration_registration_proto_rawDesc)))
	})
	return file_registration_registration_proto_rawDescData
}

var file_registration_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_registration_registration_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: registration.RegisterRequest
	(*RegisterResponse)(nil),      // 1: registration.RegisterResponse
	(*GetSchedulesRequest)(nil),   // 2: registration.GetSchedulesRequest
	(*ScheduleInfo)(nil),          // 3: registration.ScheduleInfo
	(*GetSchedulesResponse)(nil),  // 4: registration.GetSchedulesResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*common.PageRequest)(nil),    // 6: common.PageRequest
	(*common.PageResponse)(nil),   // 7: common.PageResponse
}
var file_registration_registration_proto_depIdxs = []int32{
	5, // 0: registration.RegisterResponse.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: registration.GetSchedulesRequest.page:type_name -> common.PageRequest
	3, // 2: registration.GetSchedulesResponse.schedules:type_name -> registration.ScheduleInfo
	7, // 3: registration.GetSchedulesResponse.page:type_name -> common.PageResponse
	0, // 4: registration.RegistrationService.RegisterAppointment:input_type -> registration.RegisterRequest
	2, // 5: registration.RegistrationService.GetSchedules:input_type -> registration.GetSchedulesRequest
	1, // 6: registration.RegistrationService.RegisterAppointment:output_type -> registration.RegisterResponse
	4, // 7: registration.RegistrationService.GetSchedules:output_type -> registration.GetSchedulesResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_registration_registration_proto_init() }
func file_registration_registration_proto_init() {
	if File_registration_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registration_registration_proto_rawDesc), len(file_registration_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registration_registration_proto_goTypes,
		DependencyIndexes: file_registration_registration_proto_depIdxs,
		MessageInfos:      file_registration_registration_proto_msgTypes,
	}.Build()
	File_registration_registration_proto = out.File
	file_registration_registration_proto_goTypes = nil
	file_registration_registration_proto_depIdxs = nil
}
