// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: followup/followup.proto

package followup

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建随访计划请求
type CreatePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     int64                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`         // 患者ID
	PlanName      string                 `protobuf:"bytes,2,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`             // 计划名称
	FollowupType  string                 `protobuf:"bytes,3,opt,name=followup_type,json=followupType,proto3" json:"followup_type,omitempty"` // 随访类型
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`          // 开始日期
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`                // 结束日期
	Frequency     string                 `protobuf:"bytes,6,opt,name=frequency,proto3" json:"frequency,omitempty"`                           // 随访频率（每周/每月等）
	TemplateId    string                 `protobuf:"bytes,7,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`       // 模板ID
	Creator       *common.UserContext    `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`                               // 创建人
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanRequest) Reset() {
	*x = CreatePlanRequest{}
	mi := &file_followup_followup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanRequest) ProtoMessage() {}

func (x *CreatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_followup_followup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanRequest.ProtoReflect.Descriptor instead.
func (*CreatePlanRequest) Descriptor() ([]byte, []int) {
	return file_followup_followup_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePlanRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *CreatePlanRequest) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *CreatePlanRequest) GetFollowupType() string {
	if x != nil {
		return x.FollowupType
	}
	return ""
}

func (x *CreatePlanRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreatePlanRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CreatePlanRequest) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *CreatePlanRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreatePlanRequest) GetCreator() *common.UserContext {
	if x != nil {
		return x.Creator
	}
	return nil
}

// 创建随访计划响应
type CreatePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        int64                  `protobuf:"varint,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`             // 计划ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                            // 状态
	TotalTasks    int32                  `protobuf:"varint,3,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"` // 总随访任务数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanResponse) Reset() {
	*x = CreatePlanResponse{}
	mi := &file_followup_followup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanResponse) ProtoMessage() {}

func (x *CreatePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_followup_followup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanResponse.ProtoReflect.Descriptor instead.
func (*CreatePlanResponse) Descriptor() ([]byte, []int) {
	return file_followup_followup_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlanResponse) GetPlanId() int64 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *CreatePlanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePlanResponse) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

// 添加随访记录请求
type AddRecordRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlanId           int64                  `protobuf:"varint,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`                              // 随访计划ID
	PatientId        int64                  `protobuf:"varint,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`                     // 患者ID
	RecordType       string                 `protobuf:"bytes,3,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`                   // 记录类型（电话/上门/门诊）
	Content          string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                                           // 随访内容
	PatientCondition string                 `protobuf:"bytes,5,opt,name=patient_condition,json=patientCondition,proto3" json:"patient_condition,omitempty"` // 患者状况
	Advice           string                 `protobuf:"bytes,6,opt,name=advice,proto3" json:"advice,omitempty"`                                             // 随访建议
	FollowupTime     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=followup_time,json=followupTime,proto3" json:"followup_time,omitempty"`             // 随访时间
	Recorder         *common.UserContext    `protobuf:"bytes,8,opt,name=recorder,proto3" json:"recorder,omitempty"`                                         // 记录人
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddRecordRequest) Reset() {
	*x = AddRecordRequest{}
	mi := &file_followup_followup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordRequest) ProtoMessage() {}

func (x *AddRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_followup_followup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordRequest.ProtoReflect.Descriptor instead.
func (*AddRecordRequest) Descriptor() ([]byte, []int) {
	return file_followup_followup_proto_rawDescGZIP(), []int{2}
}

func (x *AddRecordRequest) GetPlanId() int64 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *AddRecordRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *AddRecordRequest) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *AddRecordRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddRecordRequest) GetPatientCondition() string {
	if x != nil {
		return x.PatientCondition
	}
	return ""
}

func (x *AddRecordRequest) GetAdvice() string {
	if x != nil {
		return x.Advice
	}
	return ""
}

func (x *AddRecordRequest) GetFollowupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FollowupTime
	}
	return nil
}

func (x *AddRecordRequest) GetRecorder() *common.UserContext {
	if x != nil {
		return x.Recorder
	}
	return nil
}

// 添加随访记录响应
type AddRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      int64                  `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"` // 记录ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                      // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRecordResponse) Reset() {
	*x = AddRecordResponse{}
	mi := &file_followup_followup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordResponse) ProtoMessage() {}

func (x *AddRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_followup_followup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordResponse.ProtoReflect.Descriptor instead.
func (*AddRecordResponse) Descriptor() ([]byte, []int) {
	return file_followup_followup_proto_rawDescGZIP(), []int{3}
}

func (x *AddRecordResponse) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *AddRecordResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_followup_followup_proto protoreflect.FileDescriptor

const file_followup_followup_proto_rawDesc = "" +
	"\n" +
	"\x17followup/followup.proto\x12\bfollowup\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\x9c\x02\n" +
	"\x11CreatePlanRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x03R\tpatientId\x12\x1b\n" +
	"\tplan_name\x18\x02 \x01(\tR\bplanName\x12#\n" +
	"\rfollowup_type\x18\x03 \x01(\tR\ffollowupType\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x1c\n" +
	"\tfrequency\x18\x06 \x01(\tR\tfrequency\x12\x1f\n" +
	"\vtemplate_id\x18\a \x01(\tR\n" +
	"templateId\x12-\n" +
	"\acreator\x18\b \x01(\v2\x13.common.UserContextR\acreator\"f\n" +
	"\x12CreatePlanResponse\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\x03R\x06planId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vtotal_tasks\x18\x03 \x01(\x05R\n" +
	"totalTasks\"\xbc\x02\n" +
	"\x10AddRecordRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\x03R\x06planId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\x03R\tpatientId\x12\x1f\n" +
	"\vrecord_type\x18\x03 \x01(\tR\n" +
	"recordType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12+\n" +
	"\x11patient_condition\x18\x05 \x01(\tR\x10patientCondition\x12\x16\n" +
	"\x06advice\x18\x06 \x01(\tR\x06advice\x12?\n" +
	"\rfollowup_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ffollowupTime\x12/\n" +
	"\brecorder\x18\b \x01(\v2\x13.common.UserContextR\brecorder\"H\n" +
	"\x11AddRecordResponse\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x03R\brecordId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xa0\x01\n" +
	"\x0fFollowupService\x12G\n" +
	"\n" +
	"CreatePlan\x12\x1b.followup.CreatePlanRequest\x1a\x1c.followup.CreatePlanResponse\x12D\n" +
	"\tAddRecord\x12\x1a.followup.AddRecordRequest\x1a\x1b.followup.AddRecordResponseBG\n" +
	"\x1acom.hismixed.grpc.followupZ)github.com/his-mixed/go/pkg/grpc/followupb\x06proto3"

var (
	file_followup_followup_proto_rawDescOnce sync.Once
	file_followup_followup_proto_rawDescData []byte
)

func file_followup_followup_proto_rawDescGZIP() []byte {
	file_followup_followup_proto_rawDescOnce.Do(func() {
		file_followup_followup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_followup_followup_proto_rawDesc), len(file_followup_followup_proto_rawDesc)))
	})
	return file_followup_followup_proto_rawDescData
}

var file_followup_followup_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_followup_followup_proto_goTypes = []any{
	(*CreatePlanRequest)(nil),     // 0: followup.CreatePlanRequest
	(*CreatePlanResponse)(nil),    // 1: followup.CreatePlanResponse
	(*AddRecordRequest)(nil),      // 2: followup.AddRecordRequest
	(*AddRecordResponse)(nil),     // 3: followup.AddRecordResponse
	(*common.UserContext)(nil),    // 4: common.UserContext
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_followup_followup_proto_depIdxs = []int32{
	4, // 0: followup.CreatePlanRequest.creator:type_name -> common.UserContext
	5, // 1: followup.AddRecordRequest.followup_time:type_name -> google.protobuf.Timestamp
	4, // 2: followup.AddRecordRequest.recorder:type_name -> common.UserContext
	0, // 3: followup.FollowupService.CreatePlan:input_type -> followup.CreatePlanRequest
	2, // 4: followup.FollowupService.AddRecord:input_type -> followup.AddRecordRequest
	1, // 5: followup.FollowupService.CreatePlan:output_type -> followup.CreatePlanResponse
	3, // 6: followup.FollowupService.AddRecord:output_type -> followup.AddRecordResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_followup_followup_proto_init() }
func file_followup_followup_proto_init() {
	if File_followup_followup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_followup_followup_proto_rawDesc), len(file_followup_followup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_followup_followup_proto_goTypes,
		DependencyIndexes: file_followup_followup_proto_depIdxs,
		MessageInfos:      file_followup_followup_proto_msgTypes,
	}.Build()
	File_followup_followup_proto = out.File
	file_followup_followup_proto_goTypes = nil
	file_followup_followup_proto_depIdxs = nil
}
