// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: followup/followup.proto

package followup

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FollowupService_CreatePlan_FullMethodName = "/followup.FollowupService/CreatePlan"
	FollowupService_AddRecord_FullMethodName  = "/followup.FollowupService/AddRecord"
)

// FollowupServiceClient is the client API for FollowupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 随访服务
type FollowupServiceClient interface {
	// 创建随访计划
	CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*CreatePlanResponse, error)
	// 添加随访记录
	AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error)
}

type followupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFollowupServiceClient(cc grpc.ClientConnInterface) FollowupServiceClient {
	return &followupServiceClient{cc}
}

func (c *followupServiceClient) CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*CreatePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlanResponse)
	err := c.cc.Invoke(ctx, FollowupService_CreatePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followupServiceClient) AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRecordResponse)
	err := c.cc.Invoke(ctx, FollowupService_AddRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowupServiceServer is the server API for FollowupService service.
// All implementations must embed UnimplementedFollowupServiceServer
// for forward compatibility.
//
// 随访服务
type FollowupServiceServer interface {
	// 创建随访计划
	CreatePlan(context.Context, *CreatePlanRequest) (*CreatePlanResponse, error)
	// 添加随访记录
	AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error)
	mustEmbedUnimplementedFollowupServiceServer()
}

// UnimplementedFollowupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFollowupServiceServer struct{}

func (UnimplementedFollowupServiceServer) CreatePlan(context.Context, *CreatePlanRequest) (*CreatePlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlan not implemented")
}
func (UnimplementedFollowupServiceServer) AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRecord not implemented")
}
func (UnimplementedFollowupServiceServer) mustEmbedUnimplementedFollowupServiceServer() {}
func (UnimplementedFollowupServiceServer) testEmbeddedByValue()                         {}

// UnsafeFollowupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FollowupServiceServer will
// result in compilation errors.
type UnsafeFollowupServiceServer interface {
	mustEmbedUnimplementedFollowupServiceServer()
}

func RegisterFollowupServiceServer(s grpc.ServiceRegistrar, srv FollowupServiceServer) {
	// If the following call panics, it indicates UnimplementedFollowupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FollowupService_ServiceDesc, srv)
}

func _FollowupService_CreatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowupServiceServer).CreatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowupService_CreatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowupServiceServer).CreatePlan(ctx, req.(*CreatePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowupService_AddRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowupServiceServer).AddRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowupService_AddRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowupServiceServer).AddRecord(ctx, req.(*AddRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FollowupService_ServiceDesc is the grpc.ServiceDesc for FollowupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FollowupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "followup.FollowupService",
	HandlerType: (*FollowupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlan",
			Handler:    _FollowupService_CreatePlan_Handler,
		},
		{
			MethodName: "AddRecord",
			Handler:    _FollowupService_AddRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "followup/followup.proto",
}
