// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: statistics/statistics.proto

package statistics

import (
	_ "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 仪表盘请求
type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`                                  // 统计周期（今天/本周/本月）
	DepartmentId  int64                  `protobuf:"varint,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"` // 科室ID（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_statistics_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *GetDashboardRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetDashboardRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

// 仪表盘响应
type GetDashboardResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalRegistrations int64                  `protobuf:"varint,1,opt,name=total_registrations,json=totalRegistrations,proto3" json:"total_registrations,omitempty"` // 挂号总量
	TotalOutpatients   int64                  `protobuf:"varint,2,opt,name=total_outpatients,json=totalOutpatients,proto3" json:"total_outpatients,omitempty"`       // 门诊量
	TotalInpatients    int64                  `protobuf:"varint,3,opt,name=total_inpatients,json=totalInpatients,proto3" json:"total_inpatients,omitempty"`          // 住院量
	TotalPrescriptions int64                  `protobuf:"varint,4,opt,name=total_prescriptions,json=totalPrescriptions,proto3" json:"total_prescriptions,omitempty"` // 处方量
	TotalRevenue       float64                `protobuf:"fixed64,5,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`                  // 总收入
	DeptStats          []*DepartmentStat      `protobuf:"bytes,6,rep,name=dept_stats,json=deptStats,proto3" json:"dept_stats,omitempty"`                             // 各科室统计
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetDashboardResponse) Reset() {
	*x = GetDashboardResponse{}
	mi := &file_statistics_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardResponse) ProtoMessage() {}

func (x *GetDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardResponse) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *GetDashboardResponse) GetTotalRegistrations() int64 {
	if x != nil {
		return x.TotalRegistrations
	}
	return 0
}

func (x *GetDashboardResponse) GetTotalOutpatients() int64 {
	if x != nil {
		return x.TotalOutpatients
	}
	return 0
}

func (x *GetDashboardResponse) GetTotalInpatients() int64 {
	if x != nil {
		return x.TotalInpatients
	}
	return 0
}

func (x *GetDashboardResponse) GetTotalPrescriptions() int64 {
	if x != nil {
		return x.TotalPrescriptions
	}
	return 0
}

func (x *GetDashboardResponse) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *GetDashboardResponse) GetDeptStats() []*DepartmentStat {
	if x != nil {
		return x.DeptStats
	}
	return nil
}

// 科室统计
type DepartmentStat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId   int64                  `protobuf:"varint,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`      // 科室ID
	DepartmentName string                 `protobuf:"bytes,2,opt,name=department_name,json=departmentName,proto3" json:"department_name,omitempty"` // 科室名称
	VisitCount     int64                  `protobuf:"varint,3,opt,name=visit_count,json=visitCount,proto3" json:"visit_count,omitempty"`            // 就诊人次
	Revenue        float64                `protobuf:"fixed64,4,opt,name=revenue,proto3" json:"revenue,omitempty"`                                   // 收入
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DepartmentStat) Reset() {
	*x = DepartmentStat{}
	mi := &file_statistics_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentStat) ProtoMessage() {}

func (x *DepartmentStat) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentStat.ProtoReflect.Descriptor instead.
func (*DepartmentStat) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *DepartmentStat) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *DepartmentStat) GetDepartmentName() string {
	if x != nil {
		return x.DepartmentName
	}
	return ""
}

func (x *DepartmentStat) GetVisitCount() int64 {
	if x != nil {
		return x.VisitCount
	}
	return 0
}

func (x *DepartmentStat) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

// 趋势请求
type GetTrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`                                  // 指标（门诊量/收入/处方量等）
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`           // 开始日期
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`                 // 结束日期
	Granularity   string                 `protobuf:"bytes,4,opt,name=granularity,proto3" json:"granularity,omitempty"`                        // 粒度（日/周/月）
	DepartmentId  int64                  `protobuf:"varint,5,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"` // 科室ID（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendRequest) Reset() {
	*x = GetTrendRequest{}
	mi := &file_statistics_statistics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendRequest) ProtoMessage() {}

func (x *GetTrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendRequest.ProtoReflect.Descriptor instead.
func (*GetTrendRequest) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{3}
}

func (x *GetTrendRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *GetTrendRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetTrendRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetTrendRequest) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

func (x *GetTrendRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

// 趋势项
type TrendPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`     // 日期
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"` // 数值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendPoint) Reset() {
	*x = TrendPoint{}
	mi := &file_statistics_statistics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendPoint) ProtoMessage() {}

func (x *TrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendPoint.ProtoReflect.Descriptor instead.
func (*TrendPoint) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{4}
}

func (x *TrendPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TrendPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 趋势响应
type GetTrendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"` // 指标
	Points        []*TrendPoint          `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"` // 数据点
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendResponse) Reset() {
	*x = GetTrendResponse{}
	mi := &file_statistics_statistics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendResponse) ProtoMessage() {}

func (x *GetTrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendResponse.ProtoReflect.Descriptor instead.
func (*GetTrendResponse) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{5}
}

func (x *GetTrendResponse) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *GetTrendResponse) GetPoints() []*TrendPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_statistics_statistics_proto protoreflect.FileDescriptor

const file_statistics_statistics_proto_rawDesc = "" +
	"\n" +
	"\x1bstatistics/statistics.proto\x12\n" +
	"statistics\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"R\n" +
	"\x13GetDashboardRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\x03R\fdepartmentId\"\xb0\x02\n" +
	"\x14GetDashboardResponse\x12/\n" +
	"\x13total_registrations\x18\x01 \x01(\x03R\x12totalRegistrations\x12+\n" +
	"\x11total_outpatients\x18\x02 \x01(\x03R\x10totalOutpatients\x12)\n" +
	"\x10total_inpatients\x18\x03 \x01(\x03R\x0ftotalInpatients\x12/\n" +
	"\x13total_prescriptions\x18\x04 \x01(\x03R\x12totalPrescriptions\x12#\n" +
	"\rtotal_revenue\x18\x05 \x01(\x01R\ftotalRevenue\x129\n" +
	"\n" +
	"dept_stats\x18\x06 \x03(\v2\x1a.statistics.DepartmentStatR\tdeptStats\"\x99\x01\n" +
	"\x0eDepartmentStat\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\x03R\fdepartmentId\x12'\n" +
	"\x0fdepartment_name\x18\x02 \x01(\tR\x0edepartmentName\x12\x1f\n" +
	"\vvisit_count\x18\x03 \x01(\x03R\n" +
	"visitCount\x12\x18\n" +
	"\arevenue\x18\x04 \x01(\x01R\arevenue\"\xaa\x01\n" +
	"\x0fGetTrendRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12 \n" +
	"\vgranularity\x18\x04 \x01(\tR\vgranularity\x12#\n" +
	"\rdepartment_id\x18\x05 \x01(\x03R\fdepartmentId\"6\n" +
	"\n" +
	"TrendPoint\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"Z\n" +
	"\x10GetTrendResponse\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12.\n" +
	"\x06points\x18\x02 \x03(\v2\x16.statistics.TrendPointR\x06points2\xad\x01\n" +
	"\x11StatisticsService\x12Q\n" +
	"\fGetDashboard\x12\x1f.statistics.GetDashboardRequest\x1a .statistics.GetDashboardResponse\x12E\n" +
	"\bGetTrend\x12\x1b.statistics.GetTrendRequest\x1a\x1c.statistics.GetTrendResponseBK\n" +
	"\x1ccom.hismixed.grpc.statisticsZ+github.com/his-mixed/go/pkg/grpc/statisticsb\x06proto3"

var (
	file_statistics_statistics_proto_rawDescOnce sync.Once
	file_statistics_statistics_proto_rawDescData []byte
)

func file_statistics_statistics_proto_rawDescGZIP() []byte {
	file_statistics_statistics_proto_rawDescOnce.Do(func() {
		file_statistics_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_statistics_statistics_proto_rawDesc), len(file_statistics_statistics_proto_rawDesc)))
	})
	return file_statistics_statistics_proto_rawDescData
}

var file_statistics_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_statistics_statistics_proto_goTypes = []any{
	(*GetDashboardRequest)(nil),  // 0: statistics.GetDashboardRequest
	(*GetDashboardResponse)(nil), // 1: statistics.GetDashboardResponse
	(*DepartmentStat)(nil),       // 2: statistics.DepartmentStat
	(*GetTrendRequest)(nil),      // 3: statistics.GetTrendRequest
	(*TrendPoint)(nil),           // 4: statistics.TrendPoint
	(*GetTrendResponse)(nil),     // 5: statistics.GetTrendResponse
}
var file_statistics_statistics_proto_depIdxs = []int32{
	2, // 0: statistics.GetDashboardResponse.dept_stats:type_name -> statistics.DepartmentStat
	4, // 1: statistics.GetTrendResponse.points:type_name -> statistics.TrendPoint
	0, // 2: statistics.StatisticsService.GetDashboard:input_type -> statistics.GetDashboardRequest
	3, // 3: statistics.StatisticsService.GetTrend:input_type -> statistics.GetTrendRequest
	1, // 4: statistics.StatisticsService.GetDashboard:output_type -> statistics.GetDashboardResponse
	5, // 5: statistics.StatisticsService.GetTrend:output_type -> statistics.GetTrendResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_statistics_statistics_proto_init() }
func file_statistics_statistics_proto_init() {
	if File_statistics_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statistics_statistics_proto_rawDesc), len(file_statistics_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statistics_statistics_proto_goTypes,
		DependencyIndexes: file_statistics_statistics_proto_depIdxs,
		MessageInfos:      file_statistics_statistics_proto_msgTypes,
	}.Build()
	File_statistics_statistics_proto = out.File
	file_statistics_statistics_proto_goTypes = nil
	file_statistics_statistics_proto_depIdxs = nil
}
