server:
  port: 8081
spring:
  main:
    register-shutdown-hook: false
  application:
    name: his-auth
  datasource:
    url: jdbc:postgresql://localhost:15432/his_auth
    username: his_admin
    password: change_me_123
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
