// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: billing/billing.proto

package billing

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 费用项
type FeeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemType      string                 `protobuf:"bytes,1,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`                 // 费用类型（挂号费/药费/检查费/材料费等）
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                      // 关联项目ID
	ItemName      string                 `protobuf:"bytes,3,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`                 // 项目名称
	Specification string                 `protobuf:"bytes,4,opt,name=specification,proto3" json:"specification,omitempty"`                       // 规格
	UnitPrice     float64                `protobuf:"fixed64,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`            // 单价
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`                                // 数量
	Amount        float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`                                   // 金额
	SelfPayRatio  float64                `protobuf:"fixed64,8,opt,name=self_pay_ratio,json=selfPayRatio,proto3" json:"self_pay_ratio,omitempty"` // 自付比例
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeItem) Reset() {
	*x = FeeItem{}
	mi := &file_billing_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeItem) ProtoMessage() {}

func (x *FeeItem) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeItem.ProtoReflect.Descriptor instead.
func (*FeeItem) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{0}
}

func (x *FeeItem) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *FeeItem) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *FeeItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *FeeItem) GetSpecification() string {
	if x != nil {
		return x.Specification
	}
	return ""
}

func (x *FeeItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *FeeItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *FeeItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FeeItem) GetSelfPayRatio() float64 {
	if x != nil {
		return x.SelfPayRatio
	}
	return 0
}

// 计算费用请求
type CalculateFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     int64                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`            // 患者ID
	EncounterId   int64                  `protobuf:"varint,2,opt,name=encounter_id,json=encounterId,proto3" json:"encounter_id,omitempty"`      // 就诊ID
	Items         []*FeeItem             `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`                                      // 费用项目
	InsuranceType string                 `protobuf:"bytes,4,opt,name=insurance_type,json=insuranceType,proto3" json:"insurance_type,omitempty"` // 医保类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateFeeRequest) Reset() {
	*x = CalculateFeeRequest{}
	mi := &file_billing_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateFeeRequest) ProtoMessage() {}

func (x *CalculateFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateFeeRequest.ProtoReflect.Descriptor instead.
func (*CalculateFeeRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateFeeRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *CalculateFeeRequest) GetEncounterId() int64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

func (x *CalculateFeeRequest) GetItems() []*FeeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CalculateFeeRequest) GetInsuranceType() string {
	if x != nil {
		return x.InsuranceType
	}
	return ""
}

// 计算费用响应
type CalculateFeeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalAmount     float64                `protobuf:"fixed64,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`             // 总金额
	InsuranceAmount float64                `protobuf:"fixed64,2,opt,name=insurance_amount,json=insuranceAmount,proto3" json:"insurance_amount,omitempty"` // 医保支付
	SelfPayAmount   float64                `protobuf:"fixed64,3,opt,name=self_pay_amount,json=selfPayAmount,proto3" json:"self_pay_amount,omitempty"`     // 自付金额
	Details         []*FeeItem             `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`                                          // 费用明细
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CalculateFeeResponse) Reset() {
	*x = CalculateFeeResponse{}
	mi := &file_billing_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateFeeResponse) ProtoMessage() {}

func (x *CalculateFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateFeeResponse.ProtoReflect.Descriptor instead.
func (*CalculateFeeResponse) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateFeeResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CalculateFeeResponse) GetInsuranceAmount() float64 {
	if x != nil {
		return x.InsuranceAmount
	}
	return 0
}

func (x *CalculateFeeResponse) GetSelfPayAmount() float64 {
	if x != nil {
		return x.SelfPayAmount
	}
	return 0
}

func (x *CalculateFeeResponse) GetDetails() []*FeeItem {
	if x != nil {
		return x.Details
	}
	return nil
}

// 支付方式
type PaymentMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`   // 支付方式（现金/医保卡/微信/支付宝/银行卡）
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"` // 支付金额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethod) Reset() {
	*x = PaymentMethod{}
	mi := &file_billing_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethod) ProtoMessage() {}

func (x *PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethod.ProtoReflect.Descriptor instead.
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentMethod) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PaymentMethod) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// 处理支付请求
type ProcessPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     int64                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`             // 患者ID
	EncounterId   int64                  `protobuf:"varint,2,opt,name=encounter_id,json=encounterId,proto3" json:"encounter_id,omitempty"`       // 就诊ID
	FeeItemIds    []int64                `protobuf:"varint,3,rep,packed,name=fee_item_ids,json=feeItemIds,proto3" json:"fee_item_ids,omitempty"` // 待支付费用项ID
	Payments      []*PaymentMethod       `protobuf:"bytes,4,rep,name=payments,proto3" json:"payments,omitempty"`                                 // 支付方式
	Operator      *common.UserContext    `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`                                 // 操作员
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_billing_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessPaymentRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *ProcessPaymentRequest) GetEncounterId() int64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

func (x *ProcessPaymentRequest) GetFeeItemIds() []int64 {
	if x != nil {
		return x.FeeItemIds
	}
	return nil
}

func (x *ProcessPaymentRequest) GetPayments() []*PaymentMethod {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *ProcessPaymentRequest) GetOperator() *common.UserContext {
	if x != nil {
		return x.Operator
	}
	return nil
}

// 处理支付响应
type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 交易ID
	ReceiptNo     string                 `protobuf:"bytes,2,opt,name=receipt_no,json=receiptNo,proto3" json:"receipt_no,omitempty"`              // 收据号
	TotalPaid     float64                `protobuf:"fixed64,3,opt,name=total_paid,json=totalPaid,proto3" json:"total_paid,omitempty"`            // 实收金额
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                     // 状态
	PaidAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`                       // 支付时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_billing_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessPaymentResponse) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *ProcessPaymentResponse) GetReceiptNo() string {
	if x != nil {
		return x.ReceiptNo
	}
	return ""
}

func (x *ProcessPaymentResponse) GetTotalPaid() float64 {
	if x != nil {
		return x.TotalPaid
	}
	return 0
}

func (x *ProcessPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessPaymentResponse) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

var File_billing_billing_proto protoreflect.FileDescriptor

const file_billing_billing_proto_rawDesc = "" +
	"\n" +
	"\x15billing/billing.proto\x12\abilling\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xfb\x01\n" +
	"\aFeeItem\x12\x1b\n" +
	"\titem_type\x18\x01 \x01(\tR\bitemType\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x03 \x01(\tR\bitemName\x12$\n" +
	"\rspecification\x18\x04 \x01(\tR\rspecification\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x05 \x01(\x01R\tunitPrice\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12$\n" +
	"\x0eself_pay_ratio\x18\b \x01(\x01R\fselfPayRatio\"\xa6\x01\n" +
	"\x13CalculateFeeRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x03R\tpatientId\x12!\n" +
	"\fencounter_id\x18\x02 \x01(\x03R\vencounterId\x12&\n" +
	"\x05items\x18\x03 \x03(\v2\x10.billing.FeeItemR\x05items\x12%\n" +
	"\x0einsurance_type\x18\x04 \x01(\tR\rinsuranceType\"\xb8\x01\n" +
	"\x14CalculateFeeResponse\x12!\n" +
	"\ftotal_amount\x18\x01 \x01(\x01R\vtotalAmount\x12)\n" +
	"\x10insurance_amount\x18\x02 \x01(\x01R\x0finsuranceAmount\x12&\n" +
	"\x0fself_pay_amount\x18\x03 \x01(\x01R\rselfPayAmount\x12*\n" +
	"\adetails\x18\x04 \x03(\v2\x10.billing.FeeItemR\adetails\"?\n" +
	"\rPaymentMethod\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"\xe0\x01\n" +
	"\x15ProcessPaymentRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x03R\tpatientId\x12!\n" +
	"\fencounter_id\x18\x02 \x01(\x03R\vencounterId\x12 \n" +
	"\ffee_item_ids\x18\x03 \x03(\x03R\n" +
	"feeItemIds\x122\n" +
	"\bpayments\x18\x04 \x03(\v2\x16.billing.PaymentMethodR\bpayments\x12/\n" +
	"\boperator\x18\x05 \x01(\v2\x13.common.UserContextR\boperator\"\xca\x01\n" +
	"\x16ProcessPaymentResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\x12\x1d\n" +
	"\n" +
	"receipt_no\x18\x02 \x01(\tR\treceiptNo\x12\x1d\n" +
	"\n" +
	"total_paid\x18\x03 \x01(\x01R\ttotalPaid\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x123\n" +
	"\apaid_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt2\xb0\x01\n" +
	"\x0eBillingService\x12K\n" +
	"\fCalculateFee\x12\x1c.billing.CalculateFeeRequest\x1a\x1d.billing.CalculateFeeResponse\x12Q\n" +
	"\x0eProcessPayment\x12\x1e.billing.ProcessPaymentRequest\x1a\x1f.billing.ProcessPaymentResponseBE\n" +
	"\x19com.hismixed.grpc.billingZ(github.com/his-mixed/go/pkg/grpc/billingb\x06proto3"

var (
	file_billing_billing_proto_rawDescOnce sync.Once
	file_billing_billing_proto_rawDescData []byte
)

func file_billing_billing_proto_rawDescGZIP() []byte {
	file_billing_billing_proto_rawDescOnce.Do(func() {
		file_billing_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_billing_proto_rawDesc), len(file_billing_billing_proto_rawDesc)))
	})
	return file_billing_billing_proto_rawDescData
}

var file_billing_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_billing_billing_proto_goTypes = []any{
	(*FeeItem)(nil),                // 0: billing.FeeItem
	(*CalculateFeeRequest)(nil),    // 1: billing.CalculateFeeRequest
	(*CalculateFeeResponse)(nil),   // 2: billing.CalculateFeeResponse
	(*PaymentMethod)(nil),          // 3: billing.PaymentMethod
	(*ProcessPaymentRequest)(nil),  // 4: billing.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil), // 5: billing.ProcessPaymentResponse
	(*common.UserContext)(nil),     // 6: common.UserContext
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_billing_billing_proto_depIdxs = []int32{
	0, // 0: billing.CalculateFeeRequest.items:type_name -> billing.FeeItem
	0, // 1: billing.CalculateFeeResponse.details:type_name -> billing.FeeItem
	3, // 2: billing.ProcessPaymentRequest.payments:type_name -> billing.PaymentMethod
	6, // 3: billing.ProcessPaymentRequest.operator:type_name -> common.UserContext
	7, // 4: billing.ProcessPaymentResponse.paid_at:type_name -> google.protobuf.Timestamp
	1, // 5: billing.BillingService.CalculateFee:input_type -> billing.CalculateFeeRequest
	4, // 6: billing.BillingService.ProcessPayment:input_type -> billing.ProcessPaymentRequest
	2, // 7: billing.BillingService.CalculateFee:output_type -> billing.CalculateFeeResponse
	5, // 8: billing.BillingService.ProcessPayment:output_type -> billing.ProcessPaymentResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_billing_billing_proto_init() }
func file_billing_billing_proto_init() {
	if File_billing_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_billing_proto_rawDesc), len(file_billing_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_billing_proto_goTypes,
		DependencyIndexes: file_billing_billing_proto_depIdxs,
		MessageInfos:      file_billing_billing_proto_msgTypes,
	}.Build()
	File_billing_billing_proto = out.File
	file_billing_billing_proto_goTypes = nil
	file_billing_billing_proto_depIdxs = nil
}
