server:
  name: "his-examination"
  http_port: 8088
  grpc_port: 9088

database:
  host: "localhost"
  port: 15432
  user: "his_admin"
  password: "change_me_123"
  dbname: "his_examination"
  sslmode: "disable"

redis:
  addr: "localhost:6379"
  password: "change_me_456"
  db: 0

rabbitmq:
  url: "amqp://admin:change_me_789@localhost:5672/"