server:
  name: "his-gateway"
  http_port: 8080

routes:
  auth: "http://localhost:8081"
  user: "http://localhost:8082"
  registration: "http://localhost:8083"
  clinic: "http://localhost:8084"
  prescription: "http://localhost:8085"
  billing: "http://localhost:8086"
  pharmacy: "http://localhost:8087"
  examination: "http://localhost:8088"
  inpatient: "http://localhost:8089"
  schedule: "http://localhost:8090"
  outpatient: "http://localhost:8091"
  followup: "http://localhost:8092"
  health-record: "http://localhost:8093"
  notification: "http://localhost:8094"
  statistics: "http://localhost:8095"
  system: "http://localhost:8096"
  emr: "http://localhost:8097"
