server:
  name: "his-gateway"
  http_port: 8080

database:
  host: "localhost"
  port: 5432
  user: "his_admin"
  password: "change_me_123"
  sslmode: "disable"
  dbname: ""

redis:
  addr: "localhost:6379"
  password: "change_me_456"
  db: 0

rabbitmq:
  url: "amqp://admin:change_me_789@localhost:5672/"
