server:
  port: 8097
spring:
  application:
    name: his-emr
  datasource:
    url: jdbc:postgresql://localhost:5432/his_emr
    username: his_admin
    password: change_me_123
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
