// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: clinic/clinic.proto

package clinic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClinicService_CreateEncounter_FullMethodName = "/clinic.ClinicService/CreateEncounter"
	ClinicService_AddDiagnosis_FullMethodName    = "/clinic.ClinicService/AddDiagnosis"
)

// ClinicServiceClient is the client API for ClinicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 门诊服务
type ClinicServiceClient interface {
	// 创建就诊记录
	CreateEncounter(ctx context.Context, in *CreateEncounterRequest, opts ...grpc.CallOption) (*CreateEncounterResponse, error)
	// 添加诊断
	AddDiagnosis(ctx context.Context, in *AddDiagnosisRequest, opts ...grpc.CallOption) (*AddDiagnosisResponse, error)
}

type clinicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClinicServiceClient(cc grpc.ClientConnInterface) ClinicServiceClient {
	return &clinicServiceClient{cc}
}

func (c *clinicServiceClient) CreateEncounter(ctx context.Context, in *CreateEncounterRequest, opts ...grpc.CallOption) (*CreateEncounterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEncounterResponse)
	err := c.cc.Invoke(ctx, ClinicService_CreateEncounter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clinicServiceClient) AddDiagnosis(ctx context.Context, in *AddDiagnosisRequest, opts ...grpc.CallOption) (*AddDiagnosisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDiagnosisResponse)
	err := c.cc.Invoke(ctx, ClinicService_AddDiagnosis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClinicServiceServer is the server API for ClinicService service.
// All implementations must embed UnimplementedClinicServiceServer
// for forward compatibility.
//
// 门诊服务
type ClinicServiceServer interface {
	// 创建就诊记录
	CreateEncounter(context.Context, *CreateEncounterRequest) (*CreateEncounterResponse, error)
	// 添加诊断
	AddDiagnosis(context.Context, *AddDiagnosisRequest) (*AddDiagnosisResponse, error)
	mustEmbedUnimplementedClinicServiceServer()
}

// UnimplementedClinicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClinicServiceServer struct{}

func (UnimplementedClinicServiceServer) CreateEncounter(context.Context, *CreateEncounterRequest) (*CreateEncounterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEncounter not implemented")
}
func (UnimplementedClinicServiceServer) AddDiagnosis(context.Context, *AddDiagnosisRequest) (*AddDiagnosisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDiagnosis not implemented")
}
func (UnimplementedClinicServiceServer) mustEmbedUnimplementedClinicServiceServer() {}
func (UnimplementedClinicServiceServer) testEmbeddedByValue()                       {}

// UnsafeClinicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClinicServiceServer will
// result in compilation errors.
type UnsafeClinicServiceServer interface {
	mustEmbedUnimplementedClinicServiceServer()
}

func RegisterClinicServiceServer(s grpc.ServiceRegistrar, srv ClinicServiceServer) {
	// If the following call panics, it indicates UnimplementedClinicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClinicService_ServiceDesc, srv)
}

func _ClinicService_CreateEncounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEncounterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClinicServiceServer).CreateEncounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClinicService_CreateEncounter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClinicServiceServer).CreateEncounter(ctx, req.(*CreateEncounterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClinicService_AddDiagnosis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDiagnosisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClinicServiceServer).AddDiagnosis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClinicService_AddDiagnosis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClinicServiceServer).AddDiagnosis(ctx, req.(*AddDiagnosisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClinicService_ServiceDesc is the grpc.ServiceDesc for ClinicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClinicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clinic.ClinicService",
	HandlerType: (*ClinicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEncounter",
			Handler:    _ClinicService_CreateEncounter_Handler,
		},
		{
			MethodName: "AddDiagnosis",
			Handler:    _ClinicService_AddDiagnosis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clinic/clinic.proto",
}
