// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: clinic/clinic.proto

package clinic

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建就诊请求
type CreateEncounterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PatientId      int64                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`               // 患者ID
	DoctorId       int64                  `protobuf:"varint,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`                  // 医生ID
	AppointmentId  int64                  `protobuf:"varint,3,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`   // 挂号预约ID
	EncounterType  string                 `protobuf:"bytes,4,opt,name=encounter_type,json=encounterType,proto3" json:"encounter_type,omitempty"`    // 就诊类型（初诊/复诊）
	ChiefComplaint string                 `protobuf:"bytes,5,opt,name=chief_complaint,json=chiefComplaint,proto3" json:"chief_complaint,omitempty"` // 主诉
	PresentIllness string                 `protobuf:"bytes,6,opt,name=present_illness,json=presentIllness,proto3" json:"present_illness,omitempty"` // 现病史
	PastHistory    string                 `protobuf:"bytes,7,opt,name=past_history,json=pastHistory,proto3" json:"past_history,omitempty"`          // 既往史
	PhysicalExam   string                 `protobuf:"bytes,8,opt,name=physical_exam,json=physicalExam,proto3" json:"physical_exam,omitempty"`       // 体格检查
	Doctor         *common.UserContext    `protobuf:"bytes,9,opt,name=doctor,proto3" json:"doctor,omitempty"`                                       // 接诊医生
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateEncounterRequest) Reset() {
	*x = CreateEncounterRequest{}
	mi := &file_clinic_clinic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEncounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEncounterRequest) ProtoMessage() {}

func (x *CreateEncounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinic_clinic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEncounterRequest.ProtoReflect.Descriptor instead.
func (*CreateEncounterRequest) Descriptor() ([]byte, []int) {
	return file_clinic_clinic_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEncounterRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *CreateEncounterRequest) GetDoctorId() int64 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *CreateEncounterRequest) GetAppointmentId() int64 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

func (x *CreateEncounterRequest) GetEncounterType() string {
	if x != nil {
		return x.EncounterType
	}
	return ""
}

func (x *CreateEncounterRequest) GetChiefComplaint() string {
	if x != nil {
		return x.ChiefComplaint
	}
	return ""
}

func (x *CreateEncounterRequest) GetPresentIllness() string {
	if x != nil {
		return x.PresentIllness
	}
	return ""
}

func (x *CreateEncounterRequest) GetPastHistory() string {
	if x != nil {
		return x.PastHistory
	}
	return ""
}

func (x *CreateEncounterRequest) GetPhysicalExam() string {
	if x != nil {
		return x.PhysicalExam
	}
	return ""
}

func (x *CreateEncounterRequest) GetDoctor() *common.UserContext {
	if x != nil {
		return x.Doctor
	}
	return nil
}

// 创建就诊响应
type CreateEncounterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncounterId   int64                  `protobuf:"varint,1,opt,name=encounter_id,json=encounterId,proto3" json:"encounter_id,omitempty"` // 就诊ID
	EncounterNo   string                 `protobuf:"bytes,2,opt,name=encounter_no,json=encounterNo,proto3" json:"encounter_no,omitempty"`  // 就诊编号
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                               // 状态
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`        // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEncounterResponse) Reset() {
	*x = CreateEncounterResponse{}
	mi := &file_clinic_clinic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEncounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEncounterResponse) ProtoMessage() {}

func (x *CreateEncounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinic_clinic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEncounterResponse.ProtoReflect.Descriptor instead.
func (*CreateEncounterResponse) Descriptor() ([]byte, []int) {
	return file_clinic_clinic_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEncounterResponse) GetEncounterId() int64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

func (x *CreateEncounterResponse) GetEncounterNo() string {
	if x != nil {
		return x.EncounterNo
	}
	return ""
}

func (x *CreateEncounterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateEncounterResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 添加诊断请求
type AddDiagnosisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncounterId   int64                  `protobuf:"varint,1,opt,name=encounter_id,json=encounterId,proto3" json:"encounter_id,omitempty"`      // 就诊ID
	PatientId     int64                  `protobuf:"varint,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`            // 患者ID
	DiagnosisCode string                 `protobuf:"bytes,3,opt,name=diagnosis_code,json=diagnosisCode,proto3" json:"diagnosis_code,omitempty"` // 诊断编码（ICD-10）
	DiagnosisName string                 `protobuf:"bytes,4,opt,name=diagnosis_name,json=diagnosisName,proto3" json:"diagnosis_name,omitempty"` // 诊断名称
	DiagnosisType string                 `protobuf:"bytes,5,opt,name=diagnosis_type,json=diagnosisType,proto3" json:"diagnosis_type,omitempty"` // 诊断类型（主要/次要/中医）
	Sequence      int32                  `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`                               // 序号
	Doctor        *common.UserContext    `protobuf:"bytes,7,opt,name=doctor,proto3" json:"doctor,omitempty"`                                    // 诊断医生
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDiagnosisRequest) Reset() {
	*x = AddDiagnosisRequest{}
	mi := &file_clinic_clinic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDiagnosisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDiagnosisRequest) ProtoMessage() {}

func (x *AddDiagnosisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinic_clinic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDiagnosisRequest.ProtoReflect.Descriptor instead.
func (*AddDiagnosisRequest) Descriptor() ([]byte, []int) {
	return file_clinic_clinic_proto_rawDescGZIP(), []int{2}
}

func (x *AddDiagnosisRequest) GetEncounterId() int64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

func (x *AddDiagnosisRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *AddDiagnosisRequest) GetDiagnosisCode() string {
	if x != nil {
		return x.DiagnosisCode
	}
	return ""
}

func (x *AddDiagnosisRequest) GetDiagnosisName() string {
	if x != nil {
		return x.DiagnosisName
	}
	return ""
}

func (x *AddDiagnosisRequest) GetDiagnosisType() string {
	if x != nil {
		return x.DiagnosisType
	}
	return ""
}

func (x *AddDiagnosisRequest) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AddDiagnosisRequest) GetDoctor() *common.UserContext {
	if x != nil {
		return x.Doctor
	}
	return nil
}

// 添加诊断响应
type AddDiagnosisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiagnosisId   int64                  `protobuf:"varint,1,opt,name=diagnosis_id,json=diagnosisId,proto3" json:"diagnosis_id,omitempty"` // 诊断ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                               // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDiagnosisResponse) Reset() {
	*x = AddDiagnosisResponse{}
	mi := &file_clinic_clinic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDiagnosisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDiagnosisResponse) ProtoMessage() {}

func (x *AddDiagnosisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinic_clinic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDiagnosisResponse.ProtoReflect.Descriptor instead.
func (*AddDiagnosisResponse) Descriptor() ([]byte, []int) {
	return file_clinic_clinic_proto_rawDescGZIP(), []int{3}
}

func (x *AddDiagnosisResponse) GetDiagnosisId() int64 {
	if x != nil {
		return x.DiagnosisId
	}
	return 0
}

func (x *AddDiagnosisResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_clinic_clinic_proto protoreflect.FileDescriptor

const file_clinic_clinic_proto_rawDesc = "" +
	"\n" +
	"\x13clinic/clinic.proto\x12\x06clinic\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xe9\x02\n" +
	"\x16CreateEncounterRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x03R\tpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\x03R\bdoctorId\x12%\n" +
	"\x0eappointment_id\x18\x03 \x01(\x03R\rappointmentId\x12%\n" +
	"\x0eencounter_type\x18\x04 \x01(\tR\rencounterType\x12'\n" +
	"\x0fchief_complaint\x18\x05 \x01(\tR\x0echiefComplaint\x12'\n" +
	"\x0fpresent_illness\x18\x06 \x01(\tR\x0epresentIllness\x12!\n" +
	"\fpast_history\x18\a \x01(\tR\vpastHistory\x12#\n" +
	"\rphysical_exam\x18\b \x01(\tR\fphysicalExam\x12+\n" +
	"\x06doctor\x18\t \x01(\v2\x13.common.UserContextR\x06doctor\"\xb2\x01\n" +
	"\x17CreateEncounterResponse\x12!\n" +
	"\fencounter_id\x18\x01 \x01(\x03R\vencounterId\x12!\n" +
	"\fencounter_no\x18\x02 \x01(\tR\vencounterNo\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x95\x02\n" +
	"\x13AddDiagnosisRequest\x12!\n" +
	"\fencounter_id\x18\x01 \x01(\x03R\vencounterId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\x03R\tpatientId\x12%\n" +
	"\x0ediagnosis_code\x18\x03 \x01(\tR\rdiagnosisCode\x12%\n" +
	"\x0ediagnosis_name\x18\x04 \x01(\tR\rdiagnosisName\x12%\n" +
	"\x0ediagnosis_type\x18\x05 \x01(\tR\rdiagnosisType\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x05R\bsequence\x12+\n" +
	"\x06doctor\x18\a \x01(\v2\x13.common.UserContextR\x06doctor\"Q\n" +
	"\x14AddDiagnosisResponse\x12!\n" +
	"\fdiagnosis_id\x18\x01 \x01(\x03R\vdiagnosisId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xae\x01\n" +
	"\rClinicService\x12R\n" +
	"\x0fCreateEncounter\x12\x1e.clinic.CreateEncounterRequest\x1a\x1f.clinic.CreateEncounterResponse\x12I\n" +
	"\fAddDiagnosis\x12\x1b.clinic.AddDiagnosisRequest\x1a\x1c.clinic.AddDiagnosisResponseBC\n" +
	"\x18com.hismixed.grpc.clinicZ'github.com/his-mixed/go/pkg/grpc/clinicb\x06proto3"

var (
	file_clinic_clinic_proto_rawDescOnce sync.Once
	file_clinic_clinic_proto_rawDescData []byte
)

func file_clinic_clinic_proto_rawDescGZIP() []byte {
	file_clinic_clinic_proto_rawDescOnce.Do(func() {
		file_clinic_clinic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clinic_clinic_proto_rawDesc), len(file_clinic_clinic_proto_rawDesc)))
	})
	return file_clinic_clinic_proto_rawDescData
}

var file_clinic_clinic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_clinic_clinic_proto_goTypes = []any{
	(*CreateEncounterRequest)(nil),  // 0: clinic.CreateEncounterRequest
	(*CreateEncounterResponse)(nil), // 1: clinic.CreateEncounterResponse
	(*AddDiagnosisRequest)(nil),     // 2: clinic.AddDiagnosisRequest
	(*AddDiagnosisResponse)(nil),    // 3: clinic.AddDiagnosisResponse
	(*common.UserContext)(nil),      // 4: common.UserContext
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_clinic_clinic_proto_depIdxs = []int32{
	4, // 0: clinic.CreateEncounterRequest.doctor:type_name -> common.UserContext
	5, // 1: clinic.CreateEncounterResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: clinic.AddDiagnosisRequest.doctor:type_name -> common.UserContext
	0, // 3: clinic.ClinicService.CreateEncounter:input_type -> clinic.CreateEncounterRequest
	2, // 4: clinic.ClinicService.AddDiagnosis:input_type -> clinic.AddDiagnosisRequest
	1, // 5: clinic.ClinicService.CreateEncounter:output_type -> clinic.CreateEncounterResponse
	3, // 6: clinic.ClinicService.AddDiagnosis:output_type -> clinic.AddDiagnosisResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_clinic_clinic_proto_init() }
func file_clinic_clinic_proto_init() {
	if File_clinic_clinic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clinic_clinic_proto_rawDesc), len(file_clinic_clinic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clinic_clinic_proto_goTypes,
		DependencyIndexes: file_clinic_clinic_proto_depIdxs,
		MessageInfos:      file_clinic_clinic_proto_msgTypes,
	}.Build()
	File_clinic_clinic_proto = out.File
	file_clinic_clinic_proto_goTypes = nil
	file_clinic_clinic_proto_depIdxs = nil
}
