// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: health_record/health_record.proto

package health_record

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthRecordService_GetOverview_FullMethodName = "/health_record.HealthRecordService/GetOverview"
	HealthRecordService_GetTimeline_FullMethodName = "/health_record.HealthRecordService/GetTimeline"
)

// HealthRecordServiceClient is the client API for HealthRecordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 健康档案服务
type HealthRecordServiceClient interface {
	// 获取健康概况
	GetOverview(ctx context.Context, in *GetOverviewRequest, opts ...grpc.CallOption) (*GetOverviewResponse, error)
	// 获取健康时间线
	GetTimeline(ctx context.Context, in *GetTimelineRequest, opts ...grpc.CallOption) (*GetTimelineResponse, error)
}

type healthRecordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthRecordServiceClient(cc grpc.ClientConnInterface) HealthRecordServiceClient {
	return &healthRecordServiceClient{cc}
}

func (c *healthRecordServiceClient) GetOverview(ctx context.Context, in *GetOverviewRequest, opts ...grpc.CallOption) (*GetOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOverviewResponse)
	err := c.cc.Invoke(ctx, HealthRecordService_GetOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthRecordServiceClient) GetTimeline(ctx context.Context, in *GetTimelineRequest, opts ...grpc.CallOption) (*GetTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimelineResponse)
	err := c.cc.Invoke(ctx, HealthRecordService_GetTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthRecordServiceServer is the server API for HealthRecordService service.
// All implementations must embed UnimplementedHealthRecordServiceServer
// for forward compatibility.
//
// 健康档案服务
type HealthRecordServiceServer interface {
	// 获取健康概况
	GetOverview(context.Context, *GetOverviewRequest) (*GetOverviewResponse, error)
	// 获取健康时间线
	GetTimeline(context.Context, *GetTimelineRequest) (*GetTimelineResponse, error)
	mustEmbedUnimplementedHealthRecordServiceServer()
}

// UnimplementedHealthRecordServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthRecordServiceServer struct{}

func (UnimplementedHealthRecordServiceServer) GetOverview(context.Context, *GetOverviewRequest) (*GetOverviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOverview not implemented")
}
func (UnimplementedHealthRecordServiceServer) GetTimeline(context.Context, *GetTimelineRequest) (*GetTimelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTimeline not implemented")
}
func (UnimplementedHealthRecordServiceServer) mustEmbedUnimplementedHealthRecordServiceServer() {}
func (UnimplementedHealthRecordServiceServer) testEmbeddedByValue()                             {}

// UnsafeHealthRecordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthRecordServiceServer will
// result in compilation errors.
type UnsafeHealthRecordServiceServer interface {
	mustEmbedUnimplementedHealthRecordServiceServer()
}

func RegisterHealthRecordServiceServer(s grpc.ServiceRegistrar, srv HealthRecordServiceServer) {
	// If the following call panics, it indicates UnimplementedHealthRecordServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthRecordService_ServiceDesc, srv)
}

func _HealthRecordService_GetOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthRecordServiceServer).GetOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthRecordService_GetOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthRecordServiceServer).GetOverview(ctx, req.(*GetOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthRecordService_GetTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthRecordServiceServer).GetTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthRecordService_GetTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthRecordServiceServer).GetTimeline(ctx, req.(*GetTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthRecordService_ServiceDesc is the grpc.ServiceDesc for HealthRecordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthRecordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "health_record.HealthRecordService",
	HandlerType: (*HealthRecordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOverview",
			Handler:    _HealthRecordService_GetOverview_Handler,
		},
		{
			MethodName: "GetTimeline",
			Handler:    _HealthRecordService_GetTimeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health_record/health_record.proto",
}
