// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: health_record/health_record.proto

package health_record

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取概况请求
type GetOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     int64                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"` // 患者ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewRequest) Reset() {
	*x = GetOverviewRequest{}
	mi := &file_health_record_health_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewRequest) ProtoMessage() {}

func (x *GetOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_record_health_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetOverviewRequest) Descriptor() ([]byte, []int) {
	return file_health_record_health_record_proto_rawDescGZIP(), []int{0}
}

func (x *GetOverviewRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

// 健康概况
type HealthOverview struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PatientId       int64                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`                   // 患者ID
	PatientName     string                 `protobuf:"bytes,2,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`              // 患者姓名
	Gender          string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`                                           // 性别
	Age             int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`                                                // 年龄
	BloodType       string                 `protobuf:"bytes,5,opt,name=blood_type,json=bloodType,proto3" json:"blood_type,omitempty"`                    // 血型
	Allergies       string                 `protobuf:"bytes,6,opt,name=allergies,proto3" json:"allergies,omitempty"`                                     // 过敏史
	ChronicDiseases []string               `protobuf:"bytes,7,rep,name=chronic_diseases,json=chronicDiseases,proto3" json:"chronic_diseases,omitempty"`  // 慢性病
	TotalVisits     int32                  `protobuf:"varint,8,opt,name=total_visits,json=totalVisits,proto3" json:"total_visits,omitempty"`             // 总就诊次数
	TotalAdmissions int32                  `protobuf:"varint,9,opt,name=total_admissions,json=totalAdmissions,proto3" json:"total_admissions,omitempty"` // 总住院次数
	LastVisitDate   string                 `protobuf:"bytes,10,opt,name=last_visit_date,json=lastVisitDate,proto3" json:"last_visit_date,omitempty"`     // 最后就诊日期
	ActiveProblems  []string               `protobuf:"bytes,11,rep,name=active_problems,json=activeProblems,proto3" json:"active_problems,omitempty"`    // 当前健康问题
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthOverview) Reset() {
	*x = HealthOverview{}
	mi := &file_health_record_health_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthOverview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthOverview) ProtoMessage() {}

func (x *HealthOverview) ProtoReflect() protoreflect.Message {
	mi := &file_health_record_health_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthOverview.ProtoReflect.Descriptor instead.
func (*HealthOverview) Descriptor() ([]byte, []int) {
	return file_health_record_health_record_proto_rawDescGZIP(), []int{1}
}

func (x *HealthOverview) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *HealthOverview) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *HealthOverview) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *HealthOverview) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *HealthOverview) GetBloodType() string {
	if x != nil {
		return x.BloodType
	}
	return ""
}

func (x *HealthOverview) GetAllergies() string {
	if x != nil {
		return x.Allergies
	}
	return ""
}

func (x *HealthOverview) GetChronicDiseases() []string {
	if x != nil {
		return x.ChronicDiseases
	}
	return nil
}

func (x *HealthOverview) GetTotalVisits() int32 {
	if x != nil {
		return x.TotalVisits
	}
	return 0
}

func (x *HealthOverview) GetTotalAdmissions() int32 {
	if x != nil {
		return x.TotalAdmissions
	}
	return 0
}

func (x *HealthOverview) GetLastVisitDate() string {
	if x != nil {
		return x.LastVisitDate
	}
	return ""
}

func (x *HealthOverview) GetActiveProblems() []string {
	if x != nil {
		return x.ActiveProblems
	}
	return nil
}

// 获取概况响应
type GetOverviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Overview      *HealthOverview        `protobuf:"bytes,1,opt,name=overview,proto3" json:"overview,omitempty"` // 健康概况
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewResponse) Reset() {
	*x = GetOverviewResponse{}
	mi := &file_health_record_health_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewResponse) ProtoMessage() {}

func (x *GetOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_record_health_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewResponse.ProtoReflect.Descriptor instead.
func (*GetOverviewResponse) Descriptor() ([]byte, []int) {
	return file_health_record_health_record_proto_rawDescGZIP(), []int{2}
}

func (x *GetOverviewResponse) GetOverview() *HealthOverview {
	if x != nil {
		return x.Overview
	}
	return nil
}

// 获取时间线请求
type GetTimelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     int64                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"` // 患者ID
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`  // 开始日期
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`        // 结束日期
	Page          *common.PageRequest    `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`                             // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimelineRequest) Reset() {
	*x = GetTimelineRequest{}
	mi := &file_health_record_health_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimelineRequest) ProtoMessage() {}

func (x *GetTimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_record_health_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimelineRequest.ProtoReflect.Descriptor instead.
func (*GetTimelineRequest) Descriptor() ([]byte, []int) {
	return file_health_record_health_record_proto_rawDescGZIP(), []int{3}
}

func (x *GetTimelineRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *GetTimelineRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetTimelineRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetTimelineRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// 时间线条目
type TimelineEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`                                     // 日期
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`          // 事件类型（就诊/住院/检查/手术）
	EventTitle    string                 `protobuf:"bytes,3,opt,name=event_title,json=eventTitle,proto3" json:"event_title,omitempty"`       // 事件标题
	EventSummary  string                 `protobuf:"bytes,4,opt,name=event_summary,json=eventSummary,proto3" json:"event_summary,omitempty"` // 事件摘要
	Department    string                 `protobuf:"bytes,5,opt,name=department,proto3" json:"department,omitempty"`                         // 科室
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                 // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineEntry) Reset() {
	*x = TimelineEntry{}
	mi := &file_health_record_health_record_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineEntry) ProtoMessage() {}

func (x *TimelineEntry) ProtoReflect() protoreflect.Message {
	mi := &file_health_record_health_record_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineEntry.ProtoReflect.Descriptor instead.
func (*TimelineEntry) Descriptor() ([]byte, []int) {
	return file_health_record_health_record_proto_rawDescGZIP(), []int{4}
}

func (x *TimelineEntry) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TimelineEntry) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TimelineEntry) GetEventTitle() string {
	if x != nil {
		return x.EventTitle
	}
	return ""
}

func (x *TimelineEntry) GetEventSummary() string {
	if x != nil {
		return x.EventSummary
	}
	return ""
}

func (x *TimelineEntry) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *TimelineEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 获取时间线响应
type GetTimelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*TimelineEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"` // 时间线列表
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`       // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimelineResponse) Reset() {
	*x = GetTimelineResponse{}
	mi := &file_health_record_health_record_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimelineResponse) ProtoMessage() {}

func (x *GetTimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_record_health_record_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimelineResponse.ProtoReflect.Descriptor instead.
func (*GetTimelineResponse) Descriptor() ([]byte, []int) {
	return file_health_record_health_record_proto_rawDescGZIP(), []int{5}
}

func (x *GetTimelineResponse) GetEntries() []*TimelineEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetTimelineResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_health_record_health_record_proto protoreflect.FileDescriptor

const file_health_record_health_record_proto_rawDesc = "" +
	"\n" +
	"!health_record/health_record.proto\x12\rhealth_record\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"3\n" +
	"\x12GetOverviewRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x03R\tpatientId\"\x83\x03\n" +
	"\x0eHealthOverview\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x03R\tpatientId\x12!\n" +
	"\fpatient_name\x18\x02 \x01(\tR\vpatientName\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x1d\n" +
	"\n" +
	"blood_type\x18\x05 \x01(\tR\tbloodType\x12\x1c\n" +
	"\tallergies\x18\x06 \x01(\tR\tallergies\x12)\n" +
	"\x10chronic_diseases\x18\a \x03(\tR\x0fchronicDiseases\x12!\n" +
	"\ftotal_visits\x18\b \x01(\x05R\vtotalVisits\x12)\n" +
	"\x10total_admissions\x18\t \x01(\x05R\x0ftotalAdmissions\x12&\n" +
	"\x0flast_visit_date\x18\n" +
	" \x01(\tR\rlastVisitDate\x12'\n" +
	"\x0factive_problems\x18\v \x03(\tR\x0eactiveProblems\"P\n" +
	"\x13GetOverviewResponse\x129\n" +
	"\boverview\x18\x01 \x01(\v2\x1d.health_record.HealthOverviewR\boverview\"\x96\x01\n" +
	"\x12GetTimelineRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x03R\tpatientId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12'\n" +
	"\x04page\x18\x04 \x01(\v2\x13.common.PageRequestR\x04page\"\xc0\x01\n" +
	"\rTimelineEntry\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1f\n" +
	"\vevent_title\x18\x03 \x01(\tR\n" +
	"eventTitle\x12#\n" +
	"\revent_summary\x18\x04 \x01(\tR\feventSummary\x12\x1e\n" +
	"\n" +
	"department\x18\x05 \x01(\tR\n" +
	"department\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"w\n" +
	"\x13GetTimelineResponse\x126\n" +
	"\aentries\x18\x01 \x03(\v2\x1c.health_record.TimelineEntryR\aentries\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.common.PageResponseR\x04page2\xc1\x01\n" +
	"\x13HealthRecordService\x12T\n" +
	"\vGetOverview\x12!.health_record.GetOverviewRequest\x1a\".health_record.GetOverviewResponse\x12T\n" +
	"\vGetTimeline\x12!.health_record.GetTimelineRequest\x1a\".health_record.GetTimelineResponseBQ\n" +
	"\x1fcom.hismixed.grpc.health_recordZ.github.com/his-mixed/go/pkg/grpc/health_recordb\x06proto3"

var (
	file_health_record_health_record_proto_rawDescOnce sync.Once
	file_health_record_health_record_proto_rawDescData []byte
)

func file_health_record_health_record_proto_rawDescGZIP() []byte {
	file_health_record_health_record_proto_rawDescOnce.Do(func() {
		file_health_record_health_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_record_health_record_proto_rawDesc), len(file_health_record_health_record_proto_rawDesc)))
	})
	return file_health_record_health_record_proto_rawDescData
}

var file_health_record_health_record_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_health_record_health_record_proto_goTypes = []any{
	(*GetOverviewRequest)(nil),  // 0: health_record.GetOverviewRequest
	(*HealthOverview)(nil),      // 1: health_record.HealthOverview
	(*GetOverviewResponse)(nil), // 2: health_record.GetOverviewResponse
	(*GetTimelineRequest)(nil),  // 3: health_record.GetTimelineRequest
	(*TimelineEntry)(nil),       // 4: health_record.TimelineEntry
	(*GetTimelineResponse)(nil), // 5: health_record.GetTimelineResponse
	(*common.PageRequest)(nil),  // 6: common.PageRequest
	(*common.PageResponse)(nil), // 7: common.PageResponse
}
var file_health_record_health_record_proto_depIdxs = []int32{
	1, // 0: health_record.GetOverviewResponse.overview:type_name -> health_record.HealthOverview
	6, // 1: health_record.GetTimelineRequest.page:type_name -> common.PageRequest
	4, // 2: health_record.GetTimelineResponse.entries:type_name -> health_record.TimelineEntry
	7, // 3: health_record.GetTimelineResponse.page:type_name -> common.PageResponse
	0, // 4: health_record.HealthRecordService.GetOverview:input_type -> health_record.GetOverviewRequest
	3, // 5: health_record.HealthRecordService.GetTimeline:input_type -> health_record.GetTimelineRequest
	2, // 6: health_record.HealthRecordService.GetOverview:output_type -> health_record.GetOverviewResponse
	5, // 7: health_record.HealthRecordService.GetTimeline:output_type -> health_record.GetTimelineResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_health_record_health_record_proto_init() }
func file_health_record_health_record_proto_init() {
	if File_health_record_health_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_record_health_record_proto_rawDesc), len(file_health_record_health_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_record_health_record_proto_goTypes,
		DependencyIndexes: file_health_record_health_record_proto_depIdxs,
		MessageInfos:      file_health_record_health_record_proto_msgTypes,
	}.Build()
	File_health_record_health_record_proto = out.File
	file_health_record_health_record_proto_goTypes = nil
	file_health_record_health_record_proto_depIdxs = nil
}
