// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: emr/emr.proto

package emr

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建病历请求
type CreateRecordRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PatientId      int64                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`               // 患者ID
	EncounterId    int64                  `protobuf:"varint,2,opt,name=encounter_id,json=encounterId,proto3" json:"encounter_id,omitempty"`         // 就诊ID
	RecordType     string                 `protobuf:"bytes,3,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`             // 病历类型（门诊/住院/急诊）
	ChiefComplaint string                 `protobuf:"bytes,4,opt,name=chief_complaint,json=chiefComplaint,proto3" json:"chief_complaint,omitempty"` // 主诉
	PresentIllness string                 `protobuf:"bytes,5,opt,name=present_illness,json=presentIllness,proto3" json:"present_illness,omitempty"` // 现病史
	PastHistory    string                 `protobuf:"bytes,6,opt,name=past_history,json=pastHistory,proto3" json:"past_history,omitempty"`          // 既往史
	PhysicalExam   string                 `protobuf:"bytes,7,opt,name=physical_exam,json=physicalExam,proto3" json:"physical_exam,omitempty"`       // 体格检查
	AuxiliaryExam  string                 `protobuf:"bytes,8,opt,name=auxiliary_exam,json=auxiliaryExam,proto3" json:"auxiliary_exam,omitempty"`    // 辅助检查
	TreatmentPlan  string                 `protobuf:"bytes,9,opt,name=treatment_plan,json=treatmentPlan,proto3" json:"treatment_plan,omitempty"`    // 治疗计划
	MedicalAdvice  string                 `protobuf:"bytes,10,opt,name=medical_advice,json=medicalAdvice,proto3" json:"medical_advice,omitempty"`   // 医嘱
	Author         *common.UserContext    `protobuf:"bytes,11,opt,name=author,proto3" json:"author,omitempty"`                                      // 作者
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRecordRequest) Reset() {
	*x = CreateRecordRequest{}
	mi := &file_emr_emr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordRequest) ProtoMessage() {}

func (x *CreateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emr_emr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateRecordRequest) Descriptor() ([]byte, []int) {
	return file_emr_emr_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRecordRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *CreateRecordRequest) GetEncounterId() int64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

func (x *CreateRecordRequest) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *CreateRecordRequest) GetChiefComplaint() string {
	if x != nil {
		return x.ChiefComplaint
	}
	return ""
}

func (x *CreateRecordRequest) GetPresentIllness() string {
	if x != nil {
		return x.PresentIllness
	}
	return ""
}

func (x *CreateRecordRequest) GetPastHistory() string {
	if x != nil {
		return x.PastHistory
	}
	return ""
}

func (x *CreateRecordRequest) GetPhysicalExam() string {
	if x != nil {
		return x.PhysicalExam
	}
	return ""
}

func (x *CreateRecordRequest) GetAuxiliaryExam() string {
	if x != nil {
		return x.AuxiliaryExam
	}
	return ""
}

func (x *CreateRecordRequest) GetTreatmentPlan() string {
	if x != nil {
		return x.TreatmentPlan
	}
	return ""
}

func (x *CreateRecordRequest) GetMedicalAdvice() string {
	if x != nil {
		return x.MedicalAdvice
	}
	return ""
}

func (x *CreateRecordRequest) GetAuthor() *common.UserContext {
	if x != nil {
		return x.Author
	}
	return nil
}

// 创建病历响应
type CreateRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      int64                  `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"` // 病历ID
	RecordNo      string                 `protobuf:"bytes,2,opt,name=record_no,json=recordNo,proto3" json:"record_no,omitempty"`  // 病历编号
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                      // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordResponse) Reset() {
	*x = CreateRecordResponse{}
	mi := &file_emr_emr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordResponse) ProtoMessage() {}

func (x *CreateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emr_emr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateRecordResponse) Descriptor() ([]byte, []int) {
	return file_emr_emr_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRecordResponse) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *CreateRecordResponse) GetRecordNo() string {
	if x != nil {
		return x.RecordNo
	}
	return ""
}

func (x *CreateRecordResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 获取病历请求
type GetRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      int64                  `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`          // 病历ID
	PatientId     int64                  `protobuf:"varint,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`       // 患者ID
	EncounterId   int64                  `protobuf:"varint,3,opt,name=encounter_id,json=encounterId,proto3" json:"encounter_id,omitempty"` // 就诊ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_emr_emr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emr_emr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_emr_emr_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecordRequest) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *GetRecordRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *GetRecordRequest) GetEncounterId() int64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

// 病历信息
type EmrRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecordId       int64                  `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`                  // 病历ID
	PatientId      int64                  `protobuf:"varint,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`               // 患者ID
	PatientName    string                 `protobuf:"bytes,3,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`          // 患者姓名
	EncounterId    int64                  `protobuf:"varint,4,opt,name=encounter_id,json=encounterId,proto3" json:"encounter_id,omitempty"`         // 就诊ID
	RecordType     string                 `protobuf:"bytes,5,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`             // 病历类型
	ChiefComplaint string                 `protobuf:"bytes,6,opt,name=chief_complaint,json=chiefComplaint,proto3" json:"chief_complaint,omitempty"` // 主诉
	PresentIllness string                 `protobuf:"bytes,7,opt,name=present_illness,json=presentIllness,proto3" json:"present_illness,omitempty"` // 现病史
	PastHistory    string                 `protobuf:"bytes,8,opt,name=past_history,json=pastHistory,proto3" json:"past_history,omitempty"`          // 既往史
	PhysicalExam   string                 `protobuf:"bytes,9,opt,name=physical_exam,json=physicalExam,proto3" json:"physical_exam,omitempty"`       // 体格检查
	AuxiliaryExam  string                 `protobuf:"bytes,10,opt,name=auxiliary_exam,json=auxiliaryExam,proto3" json:"auxiliary_exam,omitempty"`   // 辅助检查
	TreatmentPlan  string                 `protobuf:"bytes,11,opt,name=treatment_plan,json=treatmentPlan,proto3" json:"treatment_plan,omitempty"`   // 治疗计划
	MedicalAdvice  string                 `protobuf:"bytes,12,opt,name=medical_advice,json=medicalAdvice,proto3" json:"medical_advice,omitempty"`   // 医嘱
	Status         string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`                                      // 状态
	AuthorName     string                 `protobuf:"bytes,14,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`            // 作者姓名
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`               // 创建时间
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`               // 更新时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EmrRecord) Reset() {
	*x = EmrRecord{}
	mi := &file_emr_emr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmrRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmrRecord) ProtoMessage() {}

func (x *EmrRecord) ProtoReflect() protoreflect.Message {
	mi := &file_emr_emr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmrRecord.ProtoReflect.Descriptor instead.
func (*EmrRecord) Descriptor() ([]byte, []int) {
	return file_emr_emr_proto_rawDescGZIP(), []int{3}
}

func (x *EmrRecord) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *EmrRecord) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *EmrRecord) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *EmrRecord) GetEncounterId() int64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

func (x *EmrRecord) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *EmrRecord) GetChiefComplaint() string {
	if x != nil {
		return x.ChiefComplaint
	}
	return ""
}

func (x *EmrRecord) GetPresentIllness() string {
	if x != nil {
		return x.PresentIllness
	}
	return ""
}

func (x *EmrRecord) GetPastHistory() string {
	if x != nil {
		return x.PastHistory
	}
	return ""
}

func (x *EmrRecord) GetPhysicalExam() string {
	if x != nil {
		return x.PhysicalExam
	}
	return ""
}

func (x *EmrRecord) GetAuxiliaryExam() string {
	if x != nil {
		return x.AuxiliaryExam
	}
	return ""
}

func (x *EmrRecord) GetTreatmentPlan() string {
	if x != nil {
		return x.TreatmentPlan
	}
	return ""
}

func (x *EmrRecord) GetMedicalAdvice() string {
	if x != nil {
		return x.MedicalAdvice
	}
	return ""
}

func (x *EmrRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EmrRecord) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *EmrRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EmrRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 获取病历响应
type GetRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *EmrRecord             `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"` // 病历详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordResponse) Reset() {
	*x = GetRecordResponse{}
	mi := &file_emr_emr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordResponse) ProtoMessage() {}

func (x *GetRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emr_emr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordResponse.ProtoReflect.Descriptor instead.
func (*GetRecordResponse) Descriptor() ([]byte, []int) {
	return file_emr_emr_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecordResponse) GetRecord() *EmrRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

var File_emr_emr_proto protoreflect.FileDescriptor

const file_emr_emr_proto_rawDesc = "" +
	"\n" +
	"\remr/emr.proto\x12\x03emr\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xb4\x03\n" +
	"\x13CreateRecordRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x03R\tpatientId\x12!\n" +
	"\fencounter_id\x18\x02 \x01(\x03R\vencounterId\x12\x1f\n" +
	"\vrecord_type\x18\x03 \x01(\tR\n" +
	"recordType\x12'\n" +
	"\x0fchief_complaint\x18\x04 \x01(\tR\x0echiefComplaint\x12'\n" +
	"\x0fpresent_illness\x18\x05 \x01(\tR\x0epresentIllness\x12!\n" +
	"\fpast_history\x18\x06 \x01(\tR\vpastHistory\x12#\n" +
	"\rphysical_exam\x18\a \x01(\tR\fphysicalExam\x12%\n" +
	"\x0eauxiliary_exam\x18\b \x01(\tR\rauxiliaryExam\x12%\n" +
	"\x0etreatment_plan\x18\t \x01(\tR\rtreatmentPlan\x12%\n" +
	"\x0emedical_advice\x18\n" +
	" \x01(\tR\rmedicalAdvice\x12+\n" +
	"\x06author\x18\v \x01(\v2\x13.common.UserContextR\x06author\"h\n" +
	"\x14CreateRecordResponse\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x03R\brecordId\x12\x1b\n" +
	"\trecord_no\x18\x02 \x01(\tR\brecordNo\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"q\n" +
	"\x10GetRecordRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x03R\brecordId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\x03R\tpatientId\x12!\n" +
	"\fencounter_id\x18\x03 \x01(\x03R\vencounterId\"\xec\x04\n" +
	"\tEmrRecord\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x03R\brecordId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\x03R\tpatientId\x12!\n" +
	"\fpatient_name\x18\x03 \x01(\tR\vpatientName\x12!\n" +
	"\fencounter_id\x18\x04 \x01(\x03R\vencounterId\x12\x1f\n" +
	"\vrecord_type\x18\x05 \x01(\tR\n" +
	"recordType\x12'\n" +
	"\x0fchief_complaint\x18\x06 \x01(\tR\x0echiefComplaint\x12'\n" +
	"\x0fpresent_illness\x18\a \x01(\tR\x0epresentIllness\x12!\n" +
	"\fpast_history\x18\b \x01(\tR\vpastHistory\x12#\n" +
	"\rphysical_exam\x18\t \x01(\tR\fphysicalExam\x12%\n" +
	"\x0eauxiliary_exam\x18\n" +
	" \x01(\tR\rauxiliaryExam\x12%\n" +
	"\x0etreatment_plan\x18\v \x01(\tR\rtreatmentPlan\x12%\n" +
	"\x0emedical_advice\x18\f \x01(\tR\rmedicalAdvice\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1f\n" +
	"\vauthor_name\x18\x0e \x01(\tR\n" +
	"authorName\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\";\n" +
	"\x11GetRecordResponse\x12&\n" +
	"\x06record\x18\x01 \x01(\v2\x0e.emr.EmrRecordR\x06record2\x8d\x01\n" +
	"\n" +
	"EmrService\x12C\n" +
	"\fCreateRecord\x12\x18.emr.CreateRecordRequest\x1a\x19.emr.CreateRecordResponse\x12:\n" +
	"\tGetRecord\x12\x15.emr.GetRecordRequest\x1a\x16.emr.GetRecordResponseB=\n" +
	"\x15com.hismixed.grpc.emrZ$github.com/his-mixed/go/pkg/grpc/emrb\x06proto3"

var (
	file_emr_emr_proto_rawDescOnce sync.Once
	file_emr_emr_proto_rawDescData []byte
)

func file_emr_emr_proto_rawDescGZIP() []byte {
	file_emr_emr_proto_rawDescOnce.Do(func() {
		file_emr_emr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emr_emr_proto_rawDesc), len(file_emr_emr_proto_rawDesc)))
	})
	return file_emr_emr_proto_rawDescData
}

var file_emr_emr_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_emr_emr_proto_goTypes = []any{
	(*CreateRecordRequest)(nil),   // 0: emr.CreateRecordRequest
	(*CreateRecordResponse)(nil),  // 1: emr.CreateRecordResponse
	(*GetRecordRequest)(nil),      // 2: emr.GetRecordRequest
	(*EmrRecord)(nil),             // 3: emr.EmrRecord
	(*GetRecordResponse)(nil),     // 4: emr.GetRecordResponse
	(*common.UserContext)(nil),    // 5: common.UserContext
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_emr_emr_proto_depIdxs = []int32{
	5, // 0: emr.CreateRecordRequest.author:type_name -> common.UserContext
	6, // 1: emr.EmrRecord.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: emr.EmrRecord.updated_at:type_name -> google.protobuf.Timestamp
	3, // 3: emr.GetRecordResponse.record:type_name -> emr.EmrRecord
	0, // 4: emr.EmrService.CreateRecord:input_type -> emr.CreateRecordRequest
	2, // 5: emr.EmrService.GetRecord:input_type -> emr.GetRecordRequest
	1, // 6: emr.EmrService.CreateRecord:output_type -> emr.CreateRecordResponse
	4, // 7: emr.EmrService.GetRecord:output_type -> emr.GetRecordResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_emr_emr_proto_init() }
func file_emr_emr_proto_init() {
	if File_emr_emr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emr_emr_proto_rawDesc), len(file_emr_emr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emr_emr_proto_goTypes,
		DependencyIndexes: file_emr_emr_proto_depIdxs,
		MessageInfos:      file_emr_emr_proto_msgTypes,
	}.Build()
	File_emr_emr_proto = out.File
	file_emr_emr_proto_goTypes = nil
	file_emr_emr_proto_depIdxs = nil
}
