server:
  port: 8084
spring:
  application:
    name: his-clinic
  datasource:
    url: jdbc:postgresql://localhost:5432/his_clinic
    username: his_admin
    password: change_me_123
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
