// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: schedule/schedule.proto

package schedule

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 生成排班请求（按日期范围批量生成）
type GenerateSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      int64                  `protobuf:"varint,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`             // 医生ID
	DepartmentId  int64                  `protobuf:"varint,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"` // 科室ID
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`           // 开始日期（yyyy-MM-dd）
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`                 // 结束日期
	SlotRule      string                 `protobuf:"bytes,5,opt,name=slot_rule,json=slotRule,proto3" json:"slot_rule,omitempty"`              // 时段规则（上午/下午/全天）
	MaxPerSlot    int32                  `protobuf:"varint,6,opt,name=max_per_slot,json=maxPerSlot,proto3" json:"max_per_slot,omitempty"`     // 每时段最大号数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSlotsRequest) Reset() {
	*x = GenerateSlotsRequest{}
	mi := &file_schedule_schedule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSlotsRequest) ProtoMessage() {}

func (x *GenerateSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_schedule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSlotsRequest.ProtoReflect.Descriptor instead.
func (*GenerateSlotsRequest) Descriptor() ([]byte, []int) {
	return file_schedule_schedule_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateSlotsRequest) GetDoctorId() int64 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *GenerateSlotsRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *GenerateSlotsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GenerateSlotsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GenerateSlotsRequest) GetSlotRule() string {
	if x != nil {
		return x.SlotRule
	}
	return ""
}

func (x *GenerateSlotsRequest) GetMaxPerSlot() int32 {
	if x != nil {
		return x.MaxPerSlot
	}
	return 0
}

// 生成排班响应
type GenerateSlotsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GeneratedCount int32                  `protobuf:"varint,1,opt,name=generated_count,json=generatedCount,proto3" json:"generated_count,omitempty"` // 生成的排班条目数
	Dates          []string               `protobuf:"bytes,2,rep,name=dates,proto3" json:"dates,omitempty"`                                          // 生成的日期列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateSlotsResponse) Reset() {
	*x = GenerateSlotsResponse{}
	mi := &file_schedule_schedule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSlotsResponse) ProtoMessage() {}

func (x *GenerateSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_schedule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSlotsResponse.ProtoReflect.Descriptor instead.
func (*GenerateSlotsResponse) Descriptor() ([]byte, []int) {
	return file_schedule_schedule_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateSlotsResponse) GetGeneratedCount() int32 {
	if x != nil {
		return x.GeneratedCount
	}
	return 0
}

func (x *GenerateSlotsResponse) GetDates() []string {
	if x != nil {
		return x.Dates
	}
	return nil
}

// 查询排班请求
type GetSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      int64                  `protobuf:"varint,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`             // 医生ID
	DepartmentId  int64                  `protobuf:"varint,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"` // 科室ID
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`                                      // 日期
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`           // 开始日期
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`                 // 结束日期
	Page          *common.PageRequest    `protobuf:"bytes,6,opt,name=page,proto3" json:"page,omitempty"`                                      // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSlotsRequest) Reset() {
	*x = GetSlotsRequest{}
	mi := &file_schedule_schedule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSlotsRequest) ProtoMessage() {}

func (x *GetSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_schedule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSlotsRequest.ProtoReflect.Descriptor instead.
func (*GetSlotsRequest) Descriptor() ([]byte, []int) {
	return file_schedule_schedule_proto_rawDescGZIP(), []int{2}
}

func (x *GetSlotsRequest) GetDoctorId() int64 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *GetSlotsRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *GetSlotsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetSlotsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetSlotsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetSlotsRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// 排班时段信息
type SlotInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SlotId         int64                  `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`                        // 时段ID
	DoctorId       int64                  `protobuf:"varint,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`                  // 医生ID
	DoctorName     string                 `protobuf:"bytes,3,opt,name=doctor_name,json=doctorName,proto3" json:"doctor_name,omitempty"`             // 医生姓名
	DepartmentId   int64                  `protobuf:"varint,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`      // 科室ID
	DepartmentName string                 `protobuf:"bytes,5,opt,name=department_name,json=departmentName,proto3" json:"department_name,omitempty"` // 科室名称
	Date           string                 `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`                                           // 日期
	TimeSlot       string                 `protobuf:"bytes,7,opt,name=time_slot,json=timeSlot,proto3" json:"time_slot,omitempty"`                   // 时段
	CardType       string                 `protobuf:"bytes,8,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`                   // 号别
	MaxCount       int32                  `protobuf:"varint,9,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`                  // 最大号数
	BookedCount    int32                  `protobuf:"varint,10,opt,name=booked_count,json=bookedCount,proto3" json:"booked_count,omitempty"`        // 已预约数
	Status         string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`                                      // 状态（有效/停诊）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SlotInfo) Reset() {
	*x = SlotInfo{}
	mi := &file_schedule_schedule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotInfo) ProtoMessage() {}

func (x *SlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_schedule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotInfo.ProtoReflect.Descriptor instead.
func (*SlotInfo) Descriptor() ([]byte, []int) {
	return file_schedule_schedule_proto_rawDescGZIP(), []int{3}
}

func (x *SlotInfo) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *SlotInfo) GetDoctorId() int64 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *SlotInfo) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *SlotInfo) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *SlotInfo) GetDepartmentName() string {
	if x != nil {
		return x.DepartmentName
	}
	return ""
}

func (x *SlotInfo) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SlotInfo) GetTimeSlot() string {
	if x != nil {
		return x.TimeSlot
	}
	return ""
}

func (x *SlotInfo) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *SlotInfo) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *SlotInfo) GetBookedCount() int32 {
	if x != nil {
		return x.BookedCount
	}
	return 0
}

func (x *SlotInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 查询排班响应
type GetSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*SlotInfo            `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"` // 排班列表
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`   // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSlotsResponse) Reset() {
	*x = GetSlotsResponse{}
	mi := &file_schedule_schedule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSlotsResponse) ProtoMessage() {}

func (x *GetSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_schedule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSlotsResponse.ProtoReflect.Descriptor instead.
func (*GetSlotsResponse) Descriptor() ([]byte, []int) {
	return file_schedule_schedule_proto_rawDescGZIP(), []int{4}
}

func (x *GetSlotsResponse) GetSlots() []*SlotInfo {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *GetSlotsResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_schedule_schedule_proto protoreflect.FileDescriptor

const file_schedule_schedule_proto_rawDesc = "" +
	"\n" +
	"\x17schedule/schedule.proto\x12\bschedule\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xd1\x01\n" +
	"\x14GenerateSlotsRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\x03R\bdoctorId\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\x03R\fdepartmentId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12\x1b\n" +
	"\tslot_rule\x18\x05 \x01(\tR\bslotRule\x12 \n" +
	"\fmax_per_slot\x18\x06 \x01(\x05R\n" +
	"maxPerSlot\"V\n" +
	"\x15GenerateSlotsResponse\x12'\n" +
	"\x0fgenerated_count\x18\x01 \x01(\x05R\x0egeneratedCount\x12\x14\n" +
	"\x05dates\x18\x02 \x03(\tR\x05dates\"\xca\x01\n" +
	"\x0fGetSlotsRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\x03R\bdoctorId\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\x03R\fdepartmentId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12'\n" +
	"\x04page\x18\x06 \x01(\v2\x13.common.PageRequestR\x04page\"\xd5\x02\n" +
	"\bSlotInfo\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\x03R\x06slotId\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\x03R\bdoctorId\x12\x1f\n" +
	"\vdoctor_name\x18\x03 \x01(\tR\n" +
	"doctorName\x12#\n" +
	"\rdepartment_id\x18\x04 \x01(\x03R\fdepartmentId\x12'\n" +
	"\x0fdepartment_name\x18\x05 \x01(\tR\x0edepartmentName\x12\x12\n" +
	"\x04date\x18\x06 \x01(\tR\x04date\x12\x1b\n" +
	"\ttime_slot\x18\a \x01(\tR\btimeSlot\x12\x1b\n" +
	"\tcard_type\x18\b \x01(\tR\bcardType\x12\x1b\n" +
	"\tmax_count\x18\t \x01(\x05R\bmaxCount\x12!\n" +
	"\fbooked_count\x18\n" +
	" \x01(\x05R\vbookedCount\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\"f\n" +
	"\x10GetSlotsResponse\x12(\n" +
	"\x05slots\x18\x01 \x03(\v2\x12.schedule.SlotInfoR\x05slots\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.common.PageResponseR\x04page2\xa6\x01\n" +
	"\x0fScheduleService\x12P\n" +
	"\rGenerateSlots\x12\x1e.schedule.GenerateSlotsRequest\x1a\x1f.schedule.GenerateSlotsResponse\x12A\n" +
	"\bGetSlots\x12\x19.schedule.GetSlotsRequest\x1a\x1a.schedule.GetSlotsResponseBG\n" +
	"\x1acom.hismixed.grpc.scheduleZ)github.com/his-mixed/go/pkg/grpc/scheduleb\x06proto3"

var (
	file_schedule_schedule_proto_rawDescOnce sync.Once
	file_schedule_schedule_proto_rawDescData []byte
)

func file_schedule_schedule_proto_rawDescGZIP() []byte {
	file_schedule_schedule_proto_rawDescOnce.Do(func() {
		file_schedule_schedule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schedule_schedule_proto_rawDesc), len(file_schedule_schedule_proto_rawDesc)))
	})
	return file_schedule_schedule_proto_rawDescData
}

var file_schedule_schedule_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_schedule_schedule_proto_goTypes = []any{
	(*GenerateSlotsRequest)(nil),  // 0: schedule.GenerateSlotsRequest
	(*GenerateSlotsResponse)(nil), // 1: schedule.GenerateSlotsResponse
	(*GetSlotsRequest)(nil),       // 2: schedule.GetSlotsRequest
	(*SlotInfo)(nil),              // 3: schedule.SlotInfo
	(*GetSlotsResponse)(nil),      // 4: schedule.GetSlotsResponse
	(*common.PageRequest)(nil),    // 5: common.PageRequest
	(*common.PageResponse)(nil),   // 6: common.PageResponse
}
var file_schedule_schedule_proto_depIdxs = []int32{
	5, // 0: schedule.GetSlotsRequest.page:type_name -> common.PageRequest
	3, // 1: schedule.GetSlotsResponse.slots:type_name -> schedule.SlotInfo
	6, // 2: schedule.GetSlotsResponse.page:type_name -> common.PageResponse
	0, // 3: schedule.ScheduleService.GenerateSlots:input_type -> schedule.GenerateSlotsRequest
	2, // 4: schedule.ScheduleService.GetSlots:input_type -> schedule.GetSlotsRequest
	1, // 5: schedule.ScheduleService.GenerateSlots:output_type -> schedule.GenerateSlotsResponse
	4, // 6: schedule.ScheduleService.GetSlots:output_type -> schedule.GetSlotsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_schedule_schedule_proto_init() }
func file_schedule_schedule_proto_init() {
	if File_schedule_schedule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schedule_schedule_proto_rawDesc), len(file_schedule_schedule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schedule_schedule_proto_goTypes,
		DependencyIndexes: file_schedule_schedule_proto_depIdxs,
		MessageInfos:      file_schedule_schedule_proto_msgTypes,
	}.Build()
	File_schedule_schedule_proto = out.File
	file_schedule_schedule_proto_goTypes = nil
	file_schedule_schedule_proto_depIdxs = nil
}
