// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: outpatient/outpatient.proto

package outpatient

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建会诊请求
type CreateConsultationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     int64                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`               // 患者ID
	ApplyDeptId   int64                  `protobuf:"varint,2,opt,name=apply_dept_id,json=applyDeptId,proto3" json:"apply_dept_id,omitempty"`       // 申请科室ID
	ConsultDeptId int64                  `protobuf:"varint,3,opt,name=consult_dept_id,json=consultDeptId,proto3" json:"consult_dept_id,omitempty"` // 受邀科室ID
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                                         // 会诊标题
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                             // 病情描述
	Urgency       string                 `protobuf:"bytes,6,opt,name=urgency,proto3" json:"urgency,omitempty"`                                     // 紧急程度
	Attachments   []string               `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`                             // 附件URL列表
	Applicant     *common.UserContext    `protobuf:"bytes,8,opt,name=applicant,proto3" json:"applicant,omitempty"`                                 // 申请人
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConsultationRequest) Reset() {
	*x = CreateConsultationRequest{}
	mi := &file_outpatient_outpatient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConsultationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConsultationRequest) ProtoMessage() {}

func (x *CreateConsultationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outpatient_outpatient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConsultationRequest.ProtoReflect.Descriptor instead.
func (*CreateConsultationRequest) Descriptor() ([]byte, []int) {
	return file_outpatient_outpatient_proto_rawDescGZIP(), []int{0}
}

func (x *CreateConsultationRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *CreateConsultationRequest) GetApplyDeptId() int64 {
	if x != nil {
		return x.ApplyDeptId
	}
	return 0
}

func (x *CreateConsultationRequest) GetConsultDeptId() int64 {
	if x != nil {
		return x.ConsultDeptId
	}
	return 0
}

func (x *CreateConsultationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateConsultationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateConsultationRequest) GetUrgency() string {
	if x != nil {
		return x.Urgency
	}
	return ""
}

func (x *CreateConsultationRequest) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *CreateConsultationRequest) GetApplicant() *common.UserContext {
	if x != nil {
		return x.Applicant
	}
	return nil
}

// 创建会诊响应
type CreateConsultationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConsultationId int64                  `protobuf:"varint,1,opt,name=consultation_id,json=consultationId,proto3" json:"consultation_id,omitempty"` // 会诊ID
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                        // 状态
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                 // 创建时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateConsultationResponse) Reset() {
	*x = CreateConsultationResponse{}
	mi := &file_outpatient_outpatient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConsultationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConsultationResponse) ProtoMessage() {}

func (x *CreateConsultationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outpatient_outpatient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConsultationResponse.ProtoReflect.Descriptor instead.
func (*CreateConsultationResponse) Descriptor() ([]byte, []int) {
	return file_outpatient_outpatient_proto_rawDescGZIP(), []int{1}
}

func (x *CreateConsultationResponse) GetConsultationId() int64 {
	if x != nil {
		return x.ConsultationId
	}
	return 0
}

func (x *CreateConsultationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateConsultationResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 获取消息请求
type GetMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConsultationId int64                  `protobuf:"varint,1,opt,name=consultation_id,json=consultationId,proto3" json:"consultation_id,omitempty"` // 会诊ID
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 用户ID
	Page           *common.PageRequest    `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`                                            // 分页
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_outpatient_outpatient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outpatient_outpatient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_outpatient_outpatient_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessagesRequest) GetConsultationId() int64 {
	if x != nil {
		return x.ConsultationId
	}
	return 0
}

func (x *GetMessagesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetMessagesRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// 会诊消息
type ConsultationMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                // 消息ID
	ConsultationId int64                  `protobuf:"varint,2,opt,name=consultation_id,json=consultationId,proto3" json:"consultation_id,omitempty"` // 会诊ID
	SenderId       int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                   // 发送人ID
	SenderName     string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`              // 发送人姓名
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                                      // 消息内容
	MessageType    string                 `protobuf:"bytes,6,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`           // 消息类型
	SentAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`                          // 发送时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsultationMessage) Reset() {
	*x = ConsultationMessage{}
	mi := &file_outpatient_outpatient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultationMessage) ProtoMessage() {}

func (x *ConsultationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_outpatient_outpatient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultationMessage.ProtoReflect.Descriptor instead.
func (*ConsultationMessage) Descriptor() ([]byte, []int) {
	return file_outpatient_outpatient_proto_rawDescGZIP(), []int{3}
}

func (x *ConsultationMessage) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ConsultationMessage) GetConsultationId() int64 {
	if x != nil {
		return x.ConsultationId
	}
	return 0
}

func (x *ConsultationMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ConsultationMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ConsultationMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConsultationMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ConsultationMessage) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

// 获取消息响应
type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ConsultationMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"` // 消息列表
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`         // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_outpatient_outpatient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outpatient_outpatient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_outpatient_outpatient_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessagesResponse) GetMessages() []*ConsultationMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_outpatient_outpatient_proto protoreflect.FileDescriptor

const file_outpatient_outpatient_proto_rawDesc = "" +
	"\n" +
	"\x1boutpatient/outpatient.proto\x12\n" +
	"outpatient\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xad\x02\n" +
	"\x19CreateConsultationRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x03R\tpatientId\x12\"\n" +
	"\rapply_dept_id\x18\x02 \x01(\x03R\vapplyDeptId\x12&\n" +
	"\x0fconsult_dept_id\x18\x03 \x01(\x03R\rconsultDeptId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aurgency\x18\x06 \x01(\tR\aurgency\x12 \n" +
	"\vattachments\x18\a \x03(\tR\vattachments\x121\n" +
	"\tapplicant\x18\b \x01(\v2\x13.common.UserContextR\tapplicant\"\x98\x01\n" +
	"\x1aCreateConsultationResponse\x12'\n" +
	"\x0fconsultation_id\x18\x01 \x01(\x03R\x0econsultationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x7f\n" +
	"\x12GetMessagesRequest\x12'\n" +
	"\x0fconsultation_id\x18\x01 \x01(\x03R\x0econsultationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12'\n" +
	"\x04page\x18\x03 \x01(\v2\x13.common.PageRequestR\x04page\"\x8d\x02\n" +
	"\x13ConsultationMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12'\n" +
	"\x0fconsultation_id\x18\x02 \x01(\x03R\x0econsultationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12!\n" +
	"\fmessage_type\x18\x06 \x01(\tR\vmessageType\x123\n" +
	"\asent_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"|\n" +
	"\x13GetMessagesResponse\x12;\n" +
	"\bmessages\x18\x01 \x03(\v2\x1f.outpatient.ConsultationMessageR\bmessages\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.common.PageResponseR\x04page2\xc8\x01\n" +
	"\x11OutpatientService\x12c\n" +
	"\x12CreateConsultation\x12%.outpatient.CreateConsultationRequest\x1a&.outpatient.CreateConsultationResponse\x12N\n" +
	"\vGetMessages\x12\x1e.outpatient.GetMessagesRequest\x1a\x1f.outpatient.GetMessagesResponseBK\n" +
	"\x1ccom.hismixed.grpc.outpatientZ+github.com/his-mixed/go/pkg/grpc/outpatientb\x06proto3"

var (
	file_outpatient_outpatient_proto_rawDescOnce sync.Once
	file_outpatient_outpatient_proto_rawDescData []byte
)

func file_outpatient_outpatient_proto_rawDescGZIP() []byte {
	file_outpatient_outpatient_proto_rawDescOnce.Do(func() {
		file_outpatient_outpatient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outpatient_outpatient_proto_rawDesc), len(file_outpatient_outpatient_proto_rawDesc)))
	})
	return file_outpatient_outpatient_proto_rawDescData
}

var file_outpatient_outpatient_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_outpatient_outpatient_proto_goTypes = []any{
	(*CreateConsultationRequest)(nil),  // 0: outpatient.CreateConsultationRequest
	(*CreateConsultationResponse)(nil), // 1: outpatient.CreateConsultationResponse
	(*GetMessagesRequest)(nil),         // 2: outpatient.GetMessagesRequest
	(*ConsultationMessage)(nil),        // 3: outpatient.ConsultationMessage
	(*GetMessagesResponse)(nil),        // 4: outpatient.GetMessagesResponse
	(*common.UserContext)(nil),         // 5: common.UserContext
	(*timestamppb.Timestamp)(nil),      // 6: google.protobuf.Timestamp
	(*common.PageRequest)(nil),         // 7: common.PageRequest
	(*common.PageResponse)(nil),        // 8: common.PageResponse
}
var file_outpatient_outpatient_proto_depIdxs = []int32{
	5, // 0: outpatient.CreateConsultationRequest.applicant:type_name -> common.UserContext
	6, // 1: outpatient.CreateConsultationResponse.created_at:type_name -> google.protobuf.Timestamp
	7, // 2: outpatient.GetMessagesRequest.page:type_name -> common.PageRequest
	6, // 3: outpatient.ConsultationMessage.sent_at:type_name -> google.protobuf.Timestamp
	3, // 4: outpatient.GetMessagesResponse.messages:type_name -> outpatient.ConsultationMessage
	8, // 5: outpatient.GetMessagesResponse.page:type_name -> common.PageResponse
	0, // 6: outpatient.OutpatientService.CreateConsultation:input_type -> outpatient.CreateConsultationRequest
	2, // 7: outpatient.OutpatientService.GetMessages:input_type -> outpatient.GetMessagesRequest
	1, // 8: outpatient.OutpatientService.CreateConsultation:output_type -> outpatient.CreateConsultationResponse
	4, // 9: outpatient.OutpatientService.GetMessages:output_type -> outpatient.GetMessagesResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_outpatient_outpatient_proto_init() }
func file_outpatient_outpatient_proto_init() {
	if File_outpatient_outpatient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outpatient_outpatient_proto_rawDesc), len(file_outpatient_outpatient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_outpatient_outpatient_proto_goTypes,
		DependencyIndexes: file_outpatient_outpatient_proto_depIdxs,
		MessageInfos:      file_outpatient_outpatient_proto_msgTypes,
	}.Build()
	File_outpatient_outpatient_proto = out.File
	file_outpatient_outpatient_proto_goTypes = nil
	file_outpatient_outpatient_proto_depIdxs = nil
}
