// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: outpatient/outpatient.proto

package outpatient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OutpatientService_CreateConsultation_FullMethodName = "/outpatient.OutpatientService/CreateConsultation"
	OutpatientService_GetMessages_FullMethodName        = "/outpatient.OutpatientService/GetMessages"
)

// OutpatientServiceClient is the client API for OutpatientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 院外服务（远程会诊/院外协作）
type OutpatientServiceClient interface {
	// 创建远程会诊
	CreateConsultation(ctx context.Context, in *CreateConsultationRequest, opts ...grpc.CallOption) (*CreateConsultationResponse, error)
	// 获取消息列表
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
}

type outpatientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOutpatientServiceClient(cc grpc.ClientConnInterface) OutpatientServiceClient {
	return &outpatientServiceClient{cc}
}

func (c *outpatientServiceClient) CreateConsultation(ctx context.Context, in *CreateConsultationRequest, opts ...grpc.CallOption) (*CreateConsultationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConsultationResponse)
	err := c.cc.Invoke(ctx, OutpatientService_CreateConsultation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outpatientServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, OutpatientService_GetMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutpatientServiceServer is the server API for OutpatientService service.
// All implementations must embed UnimplementedOutpatientServiceServer
// for forward compatibility.
//
// 院外服务（远程会诊/院外协作）
type OutpatientServiceServer interface {
	// 创建远程会诊
	CreateConsultation(context.Context, *CreateConsultationRequest) (*CreateConsultationResponse, error)
	// 获取消息列表
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	mustEmbedUnimplementedOutpatientServiceServer()
}

// UnimplementedOutpatientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOutpatientServiceServer struct{}

func (UnimplementedOutpatientServiceServer) CreateConsultation(context.Context, *CreateConsultationRequest) (*CreateConsultationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateConsultation not implemented")
}
func (UnimplementedOutpatientServiceServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedOutpatientServiceServer) mustEmbedUnimplementedOutpatientServiceServer() {}
func (UnimplementedOutpatientServiceServer) testEmbeddedByValue()                           {}

// UnsafeOutpatientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutpatientServiceServer will
// result in compilation errors.
type UnsafeOutpatientServiceServer interface {
	mustEmbedUnimplementedOutpatientServiceServer()
}

func RegisterOutpatientServiceServer(s grpc.ServiceRegistrar, srv OutpatientServiceServer) {
	// If the following call panics, it indicates UnimplementedOutpatientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OutpatientService_ServiceDesc, srv)
}

func _OutpatientService_CreateConsultation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConsultationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutpatientServiceServer).CreateConsultation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutpatientService_CreateConsultation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutpatientServiceServer).CreateConsultation(ctx, req.(*CreateConsultationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutpatientService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutpatientServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutpatientService_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutpatientServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OutpatientService_ServiceDesc is the grpc.ServiceDesc for OutpatientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutpatientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outpatient.OutpatientService",
	HandlerType: (*OutpatientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConsultation",
			Handler:    _OutpatientService_CreateConsultation_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _OutpatientService_GetMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "outpatient/outpatient.proto",
}
