apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: his-mixed

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgresql.yaml
  - redis.yaml
  - rabbitmq.yaml
  - nacos.yaml
  - minio.yaml
  - go-services.yaml
  - java-services.yaml
  - nginx.yaml
