apiVersion: v1
kind: Secret
metadata:
  name: his-mixed-secrets
  namespace: his-mixed
type: Opaque
data:
  DB_PASSWORD: Y2hhbmdlX21lXzEyMw==
  REDIS_PASSWORD: Y2hhbmdlX21lXzQ1Ng==
  RABBITMQ_PASSWORD: Y2hhbmdlX21lXzc4OQ==
