// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: system/system.proto

package system

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 字典列表请求
type ListDictsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DictType        string                 `protobuf:"bytes,1,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`                       // 字典类型
	Keyword         string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`                                         // 搜索关键词
	IncludeDisabled bool                   `protobuf:"varint,3,opt,name=include_disabled,json=includeDisabled,proto3" json:"include_disabled,omitempty"` // 是否包含停用项
	Page            *common.PageRequest    `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`                                               // 分页
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListDictsRequest) Reset() {
	*x = ListDictsRequest{}
	mi := &file_system_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictsRequest) ProtoMessage() {}

func (x *ListDictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictsRequest.ProtoReflect.Descriptor instead.
func (*ListDictsRequest) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{0}
}

func (x *ListDictsRequest) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *ListDictsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListDictsRequest) GetIncludeDisabled() bool {
	if x != nil {
		return x.IncludeDisabled
	}
	return false
}

func (x *ListDictsRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// 字典项
type DictItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictId        int64                  `protobuf:"varint,1,opt,name=dict_id,json=dictId,proto3" json:"dict_id,omitempty"`          // 字典ID
	DictType      string                 `protobuf:"bytes,2,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`     // 字典类型
	DictCode      string                 `protobuf:"bytes,3,opt,name=dict_code,json=dictCode,proto3" json:"dict_code,omitempty"`     // 字典编码
	DictName      string                 `protobuf:"bytes,4,opt,name=dict_name,json=dictName,proto3" json:"dict_name,omitempty"`     // 字典名称
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // 排序
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                         // 状态（启用/停用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictItem) Reset() {
	*x = DictItem{}
	mi := &file_system_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictItem) ProtoMessage() {}

func (x *DictItem) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictItem.ProtoReflect.Descriptor instead.
func (*DictItem) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{1}
}

func (x *DictItem) GetDictId() int64 {
	if x != nil {
		return x.DictId
	}
	return 0
}

func (x *DictItem) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *DictItem) GetDictCode() string {
	if x != nil {
		return x.DictCode
	}
	return ""
}

func (x *DictItem) GetDictName() string {
	if x != nil {
		return x.DictName
	}
	return ""
}

func (x *DictItem) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *DictItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 字典列表响应
type ListDictsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dicts         []*DictItem            `protobuf:"bytes,1,rep,name=dicts,proto3" json:"dicts,omitempty"` // 字典列表
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`   // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictsResponse) Reset() {
	*x = ListDictsResponse{}
	mi := &file_system_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictsResponse) ProtoMessage() {}

func (x *ListDictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictsResponse.ProtoReflect.Descriptor instead.
func (*ListDictsResponse) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{2}
}

func (x *ListDictsResponse) GetDicts() []*DictItem {
	if x != nil {
		return x.Dicts
	}
	return nil
}

func (x *ListDictsResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// 审计日志请求
type GetAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 操作用户ID
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`                                 // 操作类型
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // 资源类型
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`          // 开始时间
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                // 结束时间
	Page          *common.PageRequest    `protobuf:"bytes,6,opt,name=page,proto3" json:"page,omitempty"`                                     // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogsRequest) Reset() {
	*x = GetAuditLogsRequest{}
	mi := &file_system_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsRequest) ProtoMessage() {}

func (x *GetAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuditLogsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetAuditLogsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *GetAuditLogsRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *GetAuditLogsRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetAuditLogsRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetAuditLogsRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// 审计日志条目
type AuditLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`                     // 日志ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 用户ID
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                             // 用户名
	RealName      string                 `protobuf:"bytes,4,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`             // 真实姓名
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`                                 // 操作（创建/更新/删除/查询）
	ResourceType  string                 `protobuf:"bytes,6,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // 资源类型
	ResourceId    int64                  `protobuf:"varint,7,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`      // 资源ID
	Detail        string                 `protobuf:"bytes,8,opt,name=detail,proto3" json:"detail,omitempty"`                                 // 操作详情（JSON）
	IpAddress     string                 `protobuf:"bytes,9,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`          // IP地址
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`         // 操作时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_system_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{4}
}

func (x *AuditLog) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *AuditLog) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuditLog) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuditLog) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *AuditLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLog) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AuditLog) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *AuditLog) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AuditLog) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AuditLog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 审计日志响应
type GetAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*AuditLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"` // 日志列表
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"` // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogsResponse) Reset() {
	*x = GetAuditLogsResponse{}
	mi := &file_system_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsResponse) ProtoMessage() {}

func (x *GetAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*GetAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuditLogsResponse) GetLogs() []*AuditLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetAuditLogsResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_system_system_proto protoreflect.FileDescriptor

const file_system_system_proto_rawDesc = "" +
	"\n" +
	"\x13system/system.proto\x12\x06system\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\x9d\x01\n" +
	"\x10ListDictsRequest\x12\x1b\n" +
	"\tdict_type\x18\x01 \x01(\tR\bdictType\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12)\n" +
	"\x10include_disabled\x18\x03 \x01(\bR\x0fincludeDisabled\x12'\n" +
	"\x04page\x18\x04 \x01(\v2\x13.common.PageRequestR\x04page\"\xb1\x01\n" +
	"\bDictItem\x12\x17\n" +
	"\adict_id\x18\x01 \x01(\x03R\x06dictId\x12\x1b\n" +
	"\tdict_type\x18\x02 \x01(\tR\bdictType\x12\x1b\n" +
	"\tdict_code\x18\x03 \x01(\tR\bdictCode\x12\x1b\n" +
	"\tdict_name\x18\x04 \x01(\tR\bdictName\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"e\n" +
	"\x11ListDictsResponse\x12&\n" +
	"\x05dicts\x18\x01 \x03(\v2\x10.system.DictItemR\x05dicts\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.common.PageResponseR\x04page\"\xce\x01\n" +
	"\x13GetAuditLogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12'\n" +
	"\x04page\x18\x06 \x01(\v2\x13.common.PageRequestR\x04page\"\xc3\x02\n" +
	"\bAuditLog\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1b\n" +
	"\treal_name\x18\x04 \x01(\tR\brealName\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12#\n" +
	"\rresource_type\x18\x06 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\a \x01(\x03R\n" +
	"resourceId\x12\x16\n" +
	"\x06detail\x18\b \x01(\tR\x06detail\x12\x1d\n" +
	"\n" +
	"ip_address\x18\t \x01(\tR\tipAddress\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"f\n" +
	"\x14GetAuditLogsResponse\x12$\n" +
	"\x04logs\x18\x01 \x03(\v2\x10.system.AuditLogR\x04logs\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.common.PageResponseR\x04page2\x9c\x01\n" +
	"\rSystemService\x12@\n" +
	"\tListDicts\x12\x18.system.ListDictsRequest\x1a\x19.system.ListDictsResponse\x12I\n" +
	"\fGetAuditLogs\x12\x1b.system.GetAuditLogsRequest\x1a\x1c.system.GetAuditLogsResponseBC\n" +
	"\x18com.hismixed.grpc.systemZ'github.com/his-mixed/go/pkg/grpc/systemb\x06proto3"

var (
	file_system_system_proto_rawDescOnce sync.Once
	file_system_system_proto_rawDescData []byte
)

func file_system_system_proto_rawDescGZIP() []byte {
	file_system_system_proto_rawDescOnce.Do(func() {
		file_system_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_system_proto_rawDesc), len(file_system_system_proto_rawDesc)))
	})
	return file_system_system_proto_rawDescData
}

var file_system_system_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_system_system_proto_goTypes = []any{
	(*ListDictsRequest)(nil),      // 0: system.ListDictsRequest
	(*DictItem)(nil),              // 1: system.DictItem
	(*ListDictsResponse)(nil),     // 2: system.ListDictsResponse
	(*GetAuditLogsRequest)(nil),   // 3: system.GetAuditLogsRequest
	(*AuditLog)(nil),              // 4: system.AuditLog
	(*GetAuditLogsResponse)(nil),  // 5: system.GetAuditLogsResponse
	(*common.PageRequest)(nil),    // 6: common.PageRequest
	(*common.PageResponse)(nil),   // 7: common.PageResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_system_system_proto_depIdxs = []int32{
	6, // 0: system.ListDictsRequest.page:type_name -> common.PageRequest
	1, // 1: system.ListDictsResponse.dicts:type_name -> system.DictItem
	7, // 2: system.ListDictsResponse.page:type_name -> common.PageResponse
	6, // 3: system.GetAuditLogsRequest.page:type_name -> common.PageRequest
	8, // 4: system.AuditLog.created_at:type_name -> google.protobuf.Timestamp
	4, // 5: system.GetAuditLogsResponse.logs:type_name -> system.AuditLog
	7, // 6: system.GetAuditLogsResponse.page:type_name -> common.PageResponse
	0, // 7: system.SystemService.ListDicts:input_type -> system.ListDictsRequest
	3, // 8: system.SystemService.GetAuditLogs:input_type -> system.GetAuditLogsRequest
	2, // 9: system.SystemService.ListDicts:output_type -> system.ListDictsResponse
	5, // 10: system.SystemService.GetAuditLogs:output_type -> system.GetAuditLogsResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_system_system_proto_init() }
func file_system_system_proto_init() {
	if File_system_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_system_proto_rawDesc), len(file_system_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_system_proto_goTypes,
		DependencyIndexes: file_system_system_proto_depIdxs,
		MessageInfos:      file_system_system_proto_msgTypes,
	}.Build()
	File_system_system_proto = out.File
	file_system_system_proto_goTypes = nil
	file_system_system_proto_depIdxs = nil
}
