// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pharmacy/pharmacy.proto

package pharmacy

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 校验库存请求
type CheckStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockCheckItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 待校验药品列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockRequest) Reset() {
	*x = CheckStockRequest{}
	mi := &file_pharmacy_pharmacy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockRequest) ProtoMessage() {}

func (x *CheckStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockRequest.ProtoReflect.Descriptor instead.
func (*CheckStockRequest) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{0}
}

func (x *CheckStockRequest) GetItems() []*StockCheckItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 库存校验项
type StockCheckItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrugId        int64                  `protobuf:"varint,1,opt,name=drug_id,json=drugId,proto3" json:"drug_id,omitempty"`      // 药品ID
	DrugCode      string                 `protobuf:"bytes,2,opt,name=drug_code,json=drugCode,proto3" json:"drug_code,omitempty"` // 药品编码
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`                // 需求数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockCheckItem) Reset() {
	*x = StockCheckItem{}
	mi := &file_pharmacy_pharmacy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockCheckItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockCheckItem) ProtoMessage() {}

func (x *StockCheckItem) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockCheckItem.ProtoReflect.Descriptor instead.
func (*StockCheckItem) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{1}
}

func (x *StockCheckItem) GetDrugId() int64 {
	if x != nil {
		return x.DrugId
	}
	return 0
}

func (x *StockCheckItem) GetDrugCode() string {
	if x != nil {
		return x.DrugCode
	}
	return ""
}

func (x *StockCheckItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// 校验库存响应
type CheckStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sufficient    bool                   `protobuf:"varint,1,opt,name=sufficient,proto3" json:"sufficient,omitempty"` // 库存是否充足
	Results       []*StockResult         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`        // 逐项结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockResponse) Reset() {
	*x = CheckStockResponse{}
	mi := &file_pharmacy_pharmacy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockResponse) ProtoMessage() {}

func (x *CheckStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockResponse.ProtoReflect.Descriptor instead.
func (*CheckStockResponse) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{2}
}

func (x *CheckStockResponse) GetSufficient() bool {
	if x != nil {
		return x.Sufficient
	}
	return false
}

func (x *CheckStockResponse) GetResults() []*StockResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// 库存结果
type StockResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrugId        int64                  `protobuf:"varint,1,opt,name=drug_id,json=drugId,proto3" json:"drug_id,omitempty"`      // 药品ID
	DrugName      string                 `protobuf:"bytes,2,opt,name=drug_name,json=drugName,proto3" json:"drug_name,omitempty"` // 药品名称
	Available     int32                  `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`              // 可用库存
	Required      int32                  `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`                // 需求数量
	Enough        bool                   `protobuf:"varint,5,opt,name=enough,proto3" json:"enough,omitempty"`                    // 是否满足
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockResult) Reset() {
	*x = StockResult{}
	mi := &file_pharmacy_pharmacy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockResult) ProtoMessage() {}

func (x *StockResult) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockResult.ProtoReflect.Descriptor instead.
func (*StockResult) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{3}
}

func (x *StockResult) GetDrugId() int64 {
	if x != nil {
		return x.DrugId
	}
	return 0
}

func (x *StockResult) GetDrugName() string {
	if x != nil {
		return x.DrugName
	}
	return ""
}

func (x *StockResult) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *StockResult) GetRequired() int32 {
	if x != nil {
		return x.Required
	}
	return 0
}

func (x *StockResult) GetEnough() bool {
	if x != nil {
		return x.Enough
	}
	return false
}

// 发药请求
type DispenseDrugRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrescriptionId int64                  `protobuf:"varint,1,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"` // 处方ID
	PatientId      int64                  `protobuf:"varint,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`                // 患者ID
	Items          []*DispenseItem        `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`                                          // 发药明细
	Operator       *common.UserContext    `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`                                    // 操作人
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispenseDrugRequest) Reset() {
	*x = DispenseDrugRequest{}
	mi := &file_pharmacy_pharmacy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispenseDrugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispenseDrugRequest) ProtoMessage() {}

func (x *DispenseDrugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispenseDrugRequest.ProtoReflect.Descriptor instead.
func (*DispenseDrugRequest) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{4}
}

func (x *DispenseDrugRequest) GetPrescriptionId() int64 {
	if x != nil {
		return x.PrescriptionId
	}
	return 0
}

func (x *DispenseDrugRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *DispenseDrugRequest) GetItems() []*DispenseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DispenseDrugRequest) GetOperator() *common.UserContext {
	if x != nil {
		return x.Operator
	}
	return nil
}

// 发药明细项
type DispenseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrugId        int64                  `protobuf:"varint,1,opt,name=drug_id,json=drugId,proto3" json:"drug_id,omitempty"`            // 药品ID
	BatchNo       string                 `protobuf:"bytes,2,opt,name=batch_no,json=batchNo,proto3" json:"batch_no,omitempty"`          // 批号
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`                      // 数量
	UsageLabel    string                 `protobuf:"bytes,4,opt,name=usage_label,json=usageLabel,proto3" json:"usage_label,omitempty"` // 用法标签
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispenseItem) Reset() {
	*x = DispenseItem{}
	mi := &file_pharmacy_pharmacy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispenseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispenseItem) ProtoMessage() {}

func (x *DispenseItem) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispenseItem.ProtoReflect.Descriptor instead.
func (*DispenseItem) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{5}
}

func (x *DispenseItem) GetDrugId() int64 {
	if x != nil {
		return x.DrugId
	}
	return 0
}

func (x *DispenseItem) GetBatchNo() string {
	if x != nil {
		return x.BatchNo
	}
	return ""
}

func (x *DispenseItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *DispenseItem) GetUsageLabel() string {
	if x != nil {
		return x.UsageLabel
	}
	return ""
}

// 发药响应
type DispenseDrugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DispenseId    int64                  `protobuf:"varint,1,opt,name=dispense_id,json=dispenseId,proto3" json:"dispense_id,omitempty"`   // 发药记录ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                              // 状态
	DispensedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=dispensed_at,json=dispensedAt,proto3" json:"dispensed_at,omitempty"` // 发药时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispenseDrugResponse) Reset() {
	*x = DispenseDrugResponse{}
	mi := &file_pharmacy_pharmacy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispenseDrugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispenseDrugResponse) ProtoMessage() {}

func (x *DispenseDrugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispenseDrugResponse.ProtoReflect.Descriptor instead.
func (*DispenseDrugResponse) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{6}
}

func (x *DispenseDrugResponse) GetDispenseId() int64 {
	if x != nil {
		return x.DispenseId
	}
	return 0
}

func (x *DispenseDrugResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DispenseDrugResponse) GetDispensedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DispensedAt
	}
	return nil
}

var File_pharmacy_pharmacy_proto protoreflect.FileDescriptor

const file_pharmacy_pharmacy_proto_rawDesc = "" +
	"\n" +
	"\x17pharmacy/pharmacy.proto\x12\bpharmacy\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"C\n" +
	"\x11CheckStockRequest\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.pharmacy.StockCheckItemR\x05items\"b\n" +
	"\x0eStockCheckItem\x12\x17\n" +
	"\adrug_id\x18\x01 \x01(\x03R\x06drugId\x12\x1b\n" +
	"\tdrug_code\x18\x02 \x01(\tR\bdrugCode\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"e\n" +
	"\x12CheckStockResponse\x12\x1e\n" +
	"\n" +
	"sufficient\x18\x01 \x01(\bR\n" +
	"sufficient\x12/\n" +
	"\aresults\x18\x02 \x03(\v2\x15.pharmacy.StockResultR\aresults\"\x95\x01\n" +
	"\vStockResult\x12\x17\n" +
	"\adrug_id\x18\x01 \x01(\x03R\x06drugId\x12\x1b\n" +
	"\tdrug_name\x18\x02 \x01(\tR\bdrugName\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\x05R\tavailable\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\x05R\brequired\x12\x16\n" +
	"\x06enough\x18\x05 \x01(\bR\x06enough\"\xbc\x01\n" +
	"\x13DispenseDrugRequest\x12'\n" +
	"\x0fprescription_id\x18\x01 \x01(\x03R\x0eprescriptionId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\x03R\tpatientId\x12,\n" +
	"\x05items\x18\x03 \x03(\v2\x16.pharmacy.DispenseItemR\x05items\x12/\n" +
	"\boperator\x18\x04 \x01(\v2\x13.common.UserContextR\boperator\"\x7f\n" +
	"\fDispenseItem\x12\x17\n" +
	"\adrug_id\x18\x01 \x01(\x03R\x06drugId\x12\x19\n" +
	"\bbatch_no\x18\x02 \x01(\tR\abatchNo\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1f\n" +
	"\vusage_label\x18\x04 \x01(\tR\n" +
	"usageLabel\"\x8e\x01\n" +
	"\x14DispenseDrugResponse\x12\x1f\n" +
	"\vdispense_id\x18\x01 \x01(\x03R\n" +
	"dispenseId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12=\n" +
	"\fdispensed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vdispensedAt2\xa9\x01\n" +
	"\x0fPharmacyService\x12G\n" +
	"\n" +
	"CheckStock\x12\x1b.pharmacy.CheckStockRequest\x1a\x1c.pharmacy.CheckStockResponse\x12M\n" +
	"\fDispenseDrug\x12\x1d.pharmacy.DispenseDrugRequest\x1a\x1e.pharmacy.DispenseDrugResponseBG\n" +
	"\x1acom.hismixed.grpc.pharmacyZ)github.com/his-mixed/go/pkg/grpc/pharmacyb\x06proto3"

var (
	file_pharmacy_pharmacy_proto_rawDescOnce sync.Once
	file_pharmacy_pharmacy_proto_rawDescData []byte
)

func file_pharmacy_pharmacy_proto_rawDescGZIP() []byte {
	file_pharmacy_pharmacy_proto_rawDescOnce.Do(func() {
		file_pharmacy_pharmacy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pharmacy_pharmacy_proto_rawDesc), len(file_pharmacy_pharmacy_proto_rawDesc)))
	})
	return file_pharmacy_pharmacy_proto_rawDescData
}

var file_pharmacy_pharmacy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pharmacy_pharmacy_proto_goTypes = []any{
	(*CheckStockRequest)(nil),     // 0: pharmacy.CheckStockRequest
	(*StockCheckItem)(nil),        // 1: pharmacy.StockCheckItem
	(*CheckStockResponse)(nil),    // 2: pharmacy.CheckStockResponse
	(*StockResult)(nil),           // 3: pharmacy.StockResult
	(*DispenseDrugRequest)(nil),   // 4: pharmacy.DispenseDrugRequest
	(*DispenseItem)(nil),          // 5: pharmacy.DispenseItem
	(*DispenseDrugResponse)(nil),  // 6: pharmacy.DispenseDrugResponse
	(*common.UserContext)(nil),    // 7: common.UserContext
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_pharmacy_pharmacy_proto_depIdxs = []int32{
	1, // 0: pharmacy.CheckStockRequest.items:type_name -> pharmacy.StockCheckItem
	3, // 1: pharmacy.CheckStockResponse.results:type_name -> pharmacy.StockResult
	5, // 2: pharmacy.DispenseDrugRequest.items:type_name -> pharmacy.DispenseItem
	7, // 3: pharmacy.DispenseDrugRequest.operator:type_name -> common.UserContext
	8, // 4: pharmacy.DispenseDrugResponse.dispensed_at:type_name -> google.protobuf.Timestamp
	0, // 5: pharmacy.PharmacyService.CheckStock:input_type -> pharmacy.CheckStockRequest
	4, // 6: pharmacy.PharmacyService.DispenseDrug:input_type -> pharmacy.DispenseDrugRequest
	2, // 7: pharmacy.PharmacyService.CheckStock:output_type -> pharmacy.CheckStockResponse
	6, // 8: pharmacy.PharmacyService.DispenseDrug:output_type -> pharmacy.DispenseDrugResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pharmacy_pharmacy_proto_init() }
func file_pharmacy_pharmacy_proto_init() {
	if File_pharmacy_pharmacy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pharmacy_pharmacy_proto_rawDesc), len(file_pharmacy_pharmacy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pharmacy_pharmacy_proto_goTypes,
		DependencyIndexes: file_pharmacy_pharmacy_proto_depIdxs,
		MessageInfos:      file_pharmacy_pharmacy_proto_msgTypes,
	}.Build()
	File_pharmacy_pharmacy_proto = out.File
	file_pharmacy_pharmacy_proto_goTypes = nil
	file_pharmacy_pharmacy_proto_depIdxs = nil
}
