// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: pharmacy/pharmacy.proto

package pharmacy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PharmacyService_CheckStock_FullMethodName   = "/pharmacy.PharmacyService/CheckStock"
	PharmacyService_DispenseDrug_FullMethodName = "/pharmacy.PharmacyService/DispenseDrug"
)

// PharmacyServiceClient is the client API for PharmacyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 药房服务
type PharmacyServiceClient interface {
	// 校验库存
	CheckStock(ctx context.Context, in *CheckStockRequest, opts ...grpc.CallOption) (*CheckStockResponse, error)
	// 发药
	DispenseDrug(ctx context.Context, in *DispenseDrugRequest, opts ...grpc.CallOption) (*DispenseDrugResponse, error)
}

type pharmacyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPharmacyServiceClient(cc grpc.ClientConnInterface) PharmacyServiceClient {
	return &pharmacyServiceClient{cc}
}

func (c *pharmacyServiceClient) CheckStock(ctx context.Context, in *CheckStockRequest, opts ...grpc.CallOption) (*CheckStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckStockResponse)
	err := c.cc.Invoke(ctx, PharmacyService_CheckStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) DispenseDrug(ctx context.Context, in *DispenseDrugRequest, opts ...grpc.CallOption) (*DispenseDrugResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispenseDrugResponse)
	err := c.cc.Invoke(ctx, PharmacyService_DispenseDrug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PharmacyServiceServer is the server API for PharmacyService service.
// All implementations must embed UnimplementedPharmacyServiceServer
// for forward compatibility.
//
// 药房服务
type PharmacyServiceServer interface {
	// 校验库存
	CheckStock(context.Context, *CheckStockRequest) (*CheckStockResponse, error)
	// 发药
	DispenseDrug(context.Context, *DispenseDrugRequest) (*DispenseDrugResponse, error)
	mustEmbedUnimplementedPharmacyServiceServer()
}

// UnimplementedPharmacyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPharmacyServiceServer struct{}

func (UnimplementedPharmacyServiceServer) CheckStock(context.Context, *CheckStockRequest) (*CheckStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckStock not implemented")
}
func (UnimplementedPharmacyServiceServer) DispenseDrug(context.Context, *DispenseDrugRequest) (*DispenseDrugResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispenseDrug not implemented")
}
func (UnimplementedPharmacyServiceServer) mustEmbedUnimplementedPharmacyServiceServer() {}
func (UnimplementedPharmacyServiceServer) testEmbeddedByValue()                         {}

// UnsafePharmacyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PharmacyServiceServer will
// result in compilation errors.
type UnsafePharmacyServiceServer interface {
	mustEmbedUnimplementedPharmacyServiceServer()
}

func RegisterPharmacyServiceServer(s grpc.ServiceRegistrar, srv PharmacyServiceServer) {
	// If the following call panics, it indicates UnimplementedPharmacyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PharmacyService_ServiceDesc, srv)
}

func _PharmacyService_CheckStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).CheckStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_CheckStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).CheckStock(ctx, req.(*CheckStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_DispenseDrug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispenseDrugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).DispenseDrug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_DispenseDrug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).DispenseDrug(ctx, req.(*DispenseDrugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PharmacyService_ServiceDesc is the grpc.ServiceDesc for PharmacyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PharmacyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pharmacy.PharmacyService",
	HandlerType: (*PharmacyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckStock",
			Handler:    _PharmacyService_CheckStock_Handler,
		},
		{
			MethodName: "DispenseDrug",
			Handler:    _PharmacyService_DispenseDrug_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pharmacy/pharmacy.proto",
}
