-- HIS-Mixed 创建全部数据库
CREATE DATABASE his_registration;
CREATE DATABASE his_outpatient;
CREATE DATABASE his_pharmacy;
CREATE DATABASE his_schedule;
CREATE DATABASE his_examination;
CREATE DATABASE his_followup;
CREATE DATABASE his_notification;
CREATE DATABASE his_statistics;
CREATE DATABASE his_auth;
CREATE DATABASE his_user;
CREATE DATABASE his_clinic;
CREATE DATABASE his_emr;
CREATE DATABASE his_prescription;
CREATE DATABASE his_billing;
CREATE DATABASE his_inpatient;
CREATE DATABASE his_health_record;
CREATE DATABASE his_system;
