// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: notification/notification.proto

package notification

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送消息请求
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverIds   []int64                `protobuf:"varint,1,rep,packed,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`                                      // 接收人ID列表
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`                                                                         // 渠道（短信/站内信/推送/微信）
	TemplateCode  string                 `protobuf:"bytes,3,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`                                           // 模板编码
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 模板参数
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`                                                                             // 消息标题
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                                                                         // 消息内容（不使用模板时）
	Sender        *common.UserContext    `protobuf:"bytes,7,opt,name=sender,proto3" json:"sender,omitempty"`                                                                           // 发送人
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetReceiverIds() []int64 {
	if x != nil {
		return x.ReceiverIds
	}
	return nil
}

func (x *SendMessageRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SendMessageRequest) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *SendMessageRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *SendMessageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetSender() *common.UserContext {
	if x != nil {
		return x.Sender
	}
	return nil
}

// 发送消息响应
type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`          // 消息ID
	SuccessCount  int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 成功数
	FailCount     int32                  `protobuf:"varint,3,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`          // 失败数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SendMessageResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *SendMessageResponse) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

// 获取模板请求
type GetTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`                               // 渠道
	TemplateType  string                 `protobuf:"bytes,2,opt,name=template_type,json=templateType,proto3" json:"template_type,omitempty"` // 模板类型
	Page          *common.PageRequest    `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`                                     // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplatesRequest) Reset() {
	*x = GetTemplatesRequest{}
	mi := &file_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplatesRequest) ProtoMessage() {}

func (x *GetTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplatesRequest.ProtoReflect.Descriptor instead.
func (*GetTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *GetTemplatesRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *GetTemplatesRequest) GetTemplateType() string {
	if x != nil {
		return x.TemplateType
	}
	return ""
}

func (x *GetTemplatesRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// 消息模板
type MessageTemplate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TemplateId      int64                  `protobuf:"varint,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`               // 模板ID
	TemplateCode    string                 `protobuf:"bytes,2,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`          // 模板编码
	TemplateName    string                 `protobuf:"bytes,3,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`          // 模板名称
	Channel         string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`                                        // 渠道
	TitleTemplate   string                 `protobuf:"bytes,5,opt,name=title_template,json=titleTemplate,proto3" json:"title_template,omitempty"`       // 标题模板
	ContentTemplate string                 `protobuf:"bytes,6,opt,name=content_template,json=contentTemplate,proto3" json:"content_template,omitempty"` // 内容模板
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                                          // 状态
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageTemplate) Reset() {
	*x = MessageTemplate{}
	mi := &file_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTemplate) ProtoMessage() {}

func (x *MessageTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTemplate.ProtoReflect.Descriptor instead.
func (*MessageTemplate) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *MessageTemplate) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *MessageTemplate) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *MessageTemplate) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *MessageTemplate) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *MessageTemplate) GetTitleTemplate() string {
	if x != nil {
		return x.TitleTemplate
	}
	return ""
}

func (x *MessageTemplate) GetContentTemplate() string {
	if x != nil {
		return x.ContentTemplate
	}
	return ""
}

func (x *MessageTemplate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 获取模板响应
type GetTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*MessageTemplate     `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"` // 模板列表
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`           // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplatesResponse) Reset() {
	*x = GetTemplatesResponse{}
	mi := &file_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplatesResponse) ProtoMessage() {}

func (x *GetTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplatesResponse.ProtoReflect.Descriptor instead.
func (*GetTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetTemplatesResponse) GetTemplates() []*MessageTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *GetTemplatesResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_notification_notification_proto protoreflect.FileDescriptor

const file_notification_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fnotification/notification.proto\x12\fnotification\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xd4\x02\n" +
	"\x12SendMessageRequest\x12!\n" +
	"\freceiver_ids\x18\x01 \x03(\x03R\vreceiverIds\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12#\n" +
	"\rtemplate_code\x18\x03 \x01(\tR\ftemplateCode\x12D\n" +
	"\x06params\x18\x04 \x03(\v2,.notification.SendMessageRequest.ParamsEntryR\x06params\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12+\n" +
	"\x06sender\x18\a \x01(\v2\x13.common.UserContextR\x06sender\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\x03 \x01(\x05R\tfailCount\"}\n" +
	"\x13GetTemplatesRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12#\n" +
	"\rtemplate_type\x18\x02 \x01(\tR\ftemplateType\x12'\n" +
	"\x04page\x18\x03 \x01(\v2\x13.common.PageRequestR\x04page\"\x80\x02\n" +
	"\x0fMessageTemplate\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\x03R\n" +
	"templateId\x12#\n" +
	"\rtemplate_code\x18\x02 \x01(\tR\ftemplateCode\x12#\n" +
	"\rtemplate_name\x18\x03 \x01(\tR\ftemplateName\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12%\n" +
	"\x0etitle_template\x18\x05 \x01(\tR\rtitleTemplate\x12)\n" +
	"\x10content_template\x18\x06 \x01(\tR\x0fcontentTemplate\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"}\n" +
	"\x14GetTemplatesResponse\x12;\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1d.notification.MessageTemplateR\ttemplates\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.common.PageResponseR\x04page2\xc0\x01\n" +
	"\x13NotificationService\x12R\n" +
	"\vSendMessage\x12 .notification.SendMessageRequest\x1a!.notification.SendMessageResponse\x12U\n" +
	"\fGetTemplates\x12!.notification.GetTemplatesRequest\x1a\".notification.GetTemplatesResponseBO\n" +
	"\x1ecom.hismixed.grpc.notificationZ-github.com/his-mixed/go/pkg/grpc/notificationb\x06proto3"

var (
	file_notification_notification_proto_rawDescOnce sync.Once
	file_notification_notification_proto_rawDescData []byte
)

func file_notification_notification_proto_rawDescGZIP() []byte {
	file_notification_notification_proto_rawDescOnce.Do(func() {
		file_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)))
	})
	return file_notification_notification_proto_rawDescData
}

var file_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_notification_notification_proto_goTypes = []any{
	(*SendMessageRequest)(nil),   // 0: notification.SendMessageRequest
	(*SendMessageResponse)(nil),  // 1: notification.SendMessageResponse
	(*GetTemplatesRequest)(nil),  // 2: notification.GetTemplatesRequest
	(*MessageTemplate)(nil),      // 3: notification.MessageTemplate
	(*GetTemplatesResponse)(nil), // 4: notification.GetTemplatesResponse
	nil,                          // 5: notification.SendMessageRequest.ParamsEntry
	(*common.UserContext)(nil),   // 6: common.UserContext
	(*common.PageRequest)(nil),   // 7: common.PageRequest
	(*common.PageResponse)(nil),  // 8: common.PageResponse
}
var file_notification_notification_proto_depIdxs = []int32{
	5, // 0: notification.SendMessageRequest.params:type_name -> notification.SendMessageRequest.ParamsEntry
	6, // 1: notification.SendMessageRequest.sender:type_name -> common.UserContext
	7, // 2: notification.GetTemplatesRequest.page:type_name -> common.PageRequest
	3, // 3: notification.GetTemplatesResponse.templates:type_name -> notification.MessageTemplate
	8, // 4: notification.GetTemplatesResponse.page:type_name -> common.PageResponse
	0, // 5: notification.NotificationService.SendMessage:input_type -> notification.SendMessageRequest
	2, // 6: notification.NotificationService.GetTemplates:input_type -> notification.GetTemplatesRequest
	1, // 7: notification.NotificationService.SendMessage:output_type -> notification.SendMessageResponse
	4, // 8: notification.NotificationService.GetTemplates:output_type -> notification.GetTemplatesResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_notification_notification_proto_init() }
func file_notification_notification_proto_init() {
	if File_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_notification_proto_goTypes,
		DependencyIndexes: file_notification_notification_proto_depIdxs,
		MessageInfos:      file_notification_notification_proto_msgTypes,
	}.Build()
	File_notification_notification_proto = out.File
	file_notification_notification_proto_goTypes = nil
	file_notification_notification_proto_depIdxs = nil
}
