server:
  port: 8085
spring:
  application:
    name: his-prescription
  datasource:
    url: jdbc:postgresql://localhost:5432/his_prescription
    username: his_admin
    password: change_me_123
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
