// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: user/user.proto

package user

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取患者请求
type GetPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     int64                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"` // 患者ID
	IdCard        string                 `protobuf:"bytes,2,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`           // 身份证号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientRequest) Reset() {
	*x = GetPatientRequest{}
	mi := &file_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientRequest) ProtoMessage() {}

func (x *GetPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientRequest.ProtoReflect.Descriptor instead.
func (*GetPatientRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetPatientRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *GetPatientRequest) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

// 患者信息
type PatientInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PatientId        int64                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`                      // 患者ID
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                  // 姓名
	Gender           string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`                                              // 性别
	Birthday         string                 `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`                                          // 出生日期
	IdCard           string                 `protobuf:"bytes,5,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`                                // 身份证号
	Phone            string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`                                                // 联系电话
	Address          string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`                                            // 地址
	BloodType        string                 `protobuf:"bytes,8,opt,name=blood_type,json=bloodType,proto3" json:"blood_type,omitempty"`                       // 血型
	Allergies        string                 `protobuf:"bytes,9,opt,name=allergies,proto3" json:"allergies,omitempty"`                                        // 过敏史
	MedicalInsurance string                 `protobuf:"bytes,10,opt,name=medical_insurance,json=medicalInsurance,proto3" json:"medical_insurance,omitempty"` // 医保类型
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                      // 建档时间
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PatientInfo) Reset() {
	*x = PatientInfo{}
	mi := &file_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientInfo) ProtoMessage() {}

func (x *PatientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientInfo.ProtoReflect.Descriptor instead.
func (*PatientInfo) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *PatientInfo) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *PatientInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatientInfo) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *PatientInfo) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *PatientInfo) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *PatientInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PatientInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PatientInfo) GetBloodType() string {
	if x != nil {
		return x.BloodType
	}
	return ""
}

func (x *PatientInfo) GetAllergies() string {
	if x != nil {
		return x.Allergies
	}
	return ""
}

func (x *PatientInfo) GetMedicalInsurance() string {
	if x != nil {
		return x.MedicalInsurance
	}
	return ""
}

func (x *PatientInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 获取患者响应
type GetPatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *PatientInfo           `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"` // 患者信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientResponse) Reset() {
	*x = GetPatientResponse{}
	mi := &file_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientResponse) ProtoMessage() {}

func (x *GetPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientResponse.ProtoReflect.Descriptor instead.
func (*GetPatientResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetPatientResponse) GetPatient() *PatientInfo {
	if x != nil {
		return x.Patient
	}
	return nil
}

// 患者列表请求
type ListPatientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                      // 搜索关键词（姓名/电话/身份证）
	Gender        string                 `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`                        // 性别筛选
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // 建档开始日期
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // 建档结束日期
	Page          *common.PageRequest    `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`                            // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatientsRequest) Reset() {
	*x = ListPatientsRequest{}
	mi := &file_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientsRequest) ProtoMessage() {}

func (x *ListPatientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientsRequest.ProtoReflect.Descriptor instead.
func (*ListPatientsRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListPatientsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListPatientsRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *ListPatientsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ListPatientsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ListPatientsRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// 患者列表响应
type ListPatientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patients      []*PatientInfo         `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"` // 患者列表
	Page          *common.PageResponse   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`         // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatientsResponse) Reset() {
	*x = ListPatientsResponse{}
	mi := &file_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientsResponse) ProtoMessage() {}

func (x *ListPatientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientsResponse.ProtoReflect.Descriptor instead.
func (*ListPatientsResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *ListPatientsResponse) GetPatients() []*PatientInfo {
	if x != nil {
		return x.Patients
	}
	return nil
}

func (x *ListPatientsResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"K\n" +
	"\x11GetPatientRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x03R\tpatientId\x12\x17\n" +
	"\aid_card\x18\x02 \x01(\tR\x06idCard\"\xe2\x02\n" +
	"\vPatientInfo\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x03R\tpatientId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12\x1a\n" +
	"\bbirthday\x18\x04 \x01(\tR\bbirthday\x12\x17\n" +
	"\aid_card\x18\x05 \x01(\tR\x06idCard\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"blood_type\x18\b \x01(\tR\tbloodType\x12\x1c\n" +
	"\tallergies\x18\t \x01(\tR\tallergies\x12+\n" +
	"\x11medical_insurance\x18\n" +
	" \x01(\tR\x10medicalInsurance\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"A\n" +
	"\x12GetPatientResponse\x12+\n" +
	"\apatient\x18\x01 \x01(\v2\x11.user.PatientInfoR\apatient\"\xaa\x01\n" +
	"\x13ListPatientsRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\tR\x06gender\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12'\n" +
	"\x04page\x18\x05 \x01(\v2\x13.common.PageRequestR\x04page\"o\n" +
	"\x14ListPatientsResponse\x12-\n" +
	"\bpatients\x18\x01 \x03(\v2\x11.user.PatientInfoR\bpatients\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.common.PageResponseR\x04page2\x95\x01\n" +
	"\vUserService\x12?\n" +
	"\n" +
	"GetPatient\x12\x17.user.GetPatientRequest\x1a\x18.user.GetPatientResponse\x12E\n" +
	"\fListPatients\x12\x19.user.ListPatientsRequest\x1a\x1a.user.ListPatientsResponseB?\n" +
	"\x16com.hismixed.grpc.userZ%github.com/his-mixed/go/pkg/grpc/userb\x06proto3"

var (
	file_user_user_proto_rawDescOnce sync.Once
	file_user_user_proto_rawDescData []byte
)

func file_user_user_proto_rawDescGZIP() []byte {
	file_user_user_proto_rawDescOnce.Do(func() {
		file_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)))
	})
	return file_user_user_proto_rawDescData
}

var file_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_user_proto_goTypes = []any{
	(*GetPatientRequest)(nil),     // 0: user.GetPatientRequest
	(*PatientInfo)(nil),           // 1: user.PatientInfo
	(*GetPatientResponse)(nil),    // 2: user.GetPatientResponse
	(*ListPatientsRequest)(nil),   // 3: user.ListPatientsRequest
	(*ListPatientsResponse)(nil),  // 4: user.ListPatientsResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*common.PageRequest)(nil),    // 6: common.PageRequest
	(*common.PageResponse)(nil),   // 7: common.PageResponse
}
var file_user_user_proto_depIdxs = []int32{
	5, // 0: user.PatientInfo.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: user.GetPatientResponse.patient:type_name -> user.PatientInfo
	6, // 2: user.ListPatientsRequest.page:type_name -> common.PageRequest
	1, // 3: user.ListPatientsResponse.patients:type_name -> user.PatientInfo
	7, // 4: user.ListPatientsResponse.page:type_name -> common.PageResponse
	0, // 5: user.UserService.GetPatient:input_type -> user.GetPatientRequest
	3, // 6: user.UserService.ListPatients:input_type -> user.ListPatientsRequest
	2, // 7: user.UserService.GetPatient:output_type -> user.GetPatientResponse
	4, // 8: user.UserService.ListPatients:output_type -> user.ListPatientsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
		MessageInfos:      file_user_user_proto_msgTypes,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
