server:
  port: 8096
spring:
  application:
    name: his-system
  datasource:
    url: jdbc:postgresql://localhost:5432/his_system
    username: his_admin
    password: change_me_123
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
