// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: prescription/prescription.proto

package prescription

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrescriptionService_CreatePrescription_FullMethodName = "/prescription.PrescriptionService/CreatePrescription"
	PrescriptionService_SubmitReview_FullMethodName       = "/prescription.PrescriptionService/SubmitReview"
)

// PrescriptionServiceClient is the client API for PrescriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 处方服务
type PrescriptionServiceClient interface {
	// 创建处方
	CreatePrescription(ctx context.Context, in *CreatePrescriptionRequest, opts ...grpc.CallOption) (*CreatePrescriptionResponse, error)
	// 提交审核
	SubmitReview(ctx context.Context, in *SubmitReviewRequest, opts ...grpc.CallOption) (*SubmitReviewResponse, error)
}

type prescriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrescriptionServiceClient(cc grpc.ClientConnInterface) PrescriptionServiceClient {
	return &prescriptionServiceClient{cc}
}

func (c *prescriptionServiceClient) CreatePrescription(ctx context.Context, in *CreatePrescriptionRequest, opts ...grpc.CallOption) (*CreatePrescriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePrescriptionResponse)
	err := c.cc.Invoke(ctx, PrescriptionService_CreatePrescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prescriptionServiceClient) SubmitReview(ctx context.Context, in *SubmitReviewRequest, opts ...grpc.CallOption) (*SubmitReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitReviewResponse)
	err := c.cc.Invoke(ctx, PrescriptionService_SubmitReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrescriptionServiceServer is the server API for PrescriptionService service.
// All implementations must embed UnimplementedPrescriptionServiceServer
// for forward compatibility.
//
// 处方服务
type PrescriptionServiceServer interface {
	// 创建处方
	CreatePrescription(context.Context, *CreatePrescriptionRequest) (*CreatePrescriptionResponse, error)
	// 提交审核
	SubmitReview(context.Context, *SubmitReviewRequest) (*SubmitReviewResponse, error)
	mustEmbedUnimplementedPrescriptionServiceServer()
}

// UnimplementedPrescriptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrescriptionServiceServer struct{}

func (UnimplementedPrescriptionServiceServer) CreatePrescription(context.Context, *CreatePrescriptionRequest) (*CreatePrescriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePrescription not implemented")
}
func (UnimplementedPrescriptionServiceServer) SubmitReview(context.Context, *SubmitReviewRequest) (*SubmitReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitReview not implemented")
}
func (UnimplementedPrescriptionServiceServer) mustEmbedUnimplementedPrescriptionServiceServer() {}
func (UnimplementedPrescriptionServiceServer) testEmbeddedByValue()                             {}

// UnsafePrescriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrescriptionServiceServer will
// result in compilation errors.
type UnsafePrescriptionServiceServer interface {
	mustEmbedUnimplementedPrescriptionServiceServer()
}

func RegisterPrescriptionServiceServer(s grpc.ServiceRegistrar, srv PrescriptionServiceServer) {
	// If the following call panics, it indicates UnimplementedPrescriptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrescriptionService_ServiceDesc, srv)
}

func _PrescriptionService_CreatePrescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePrescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrescriptionServiceServer).CreatePrescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrescriptionService_CreatePrescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrescriptionServiceServer).CreatePrescription(ctx, req.(*CreatePrescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrescriptionService_SubmitReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrescriptionServiceServer).SubmitReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrescriptionService_SubmitReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrescriptionServiceServer).SubmitReview(ctx, req.(*SubmitReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrescriptionService_ServiceDesc is the grpc.ServiceDesc for PrescriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrescriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prescription.PrescriptionService",
	HandlerType: (*PrescriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePrescription",
			Handler:    _PrescriptionService_CreatePrescription_Handler,
		},
		{
			MethodName: "SubmitReview",
			Handler:    _PrescriptionService_SubmitReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prescription/prescription.proto",
}
