// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: prescription/prescription.proto

package prescription

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 处方药品项
type PrescriptionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrugId        int64                  `protobuf:"varint,1,opt,name=drug_id,json=drugId,proto3" json:"drug_id,omitempty"`            // 药品ID
	DrugName      string                 `protobuf:"bytes,2,opt,name=drug_name,json=drugName,proto3" json:"drug_name,omitempty"`       // 药品名称
	Specification string                 `protobuf:"bytes,3,opt,name=specification,proto3" json:"specification,omitempty"`             // 规格
	UsageLabel    string                 `protobuf:"bytes,4,opt,name=usage_label,json=usageLabel,proto3" json:"usage_label,omitempty"` // 用法（口服/外用等）
	Dosage        string                 `protobuf:"bytes,5,opt,name=dosage,proto3" json:"dosage,omitempty"`                           // 用量
	Frequency     string                 `protobuf:"bytes,6,opt,name=frequency,proto3" json:"frequency,omitempty"`                     // 频次
	Days          int32                  `protobuf:"varint,7,opt,name=days,proto3" json:"days,omitempty"`                              // 天数
	Quantity      int32                  `protobuf:"varint,8,opt,name=quantity,proto3" json:"quantity,omitempty"`                      // 数量
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`                           // 备注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrescriptionItem) Reset() {
	*x = PrescriptionItem{}
	mi := &file_prescription_prescription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrescriptionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrescriptionItem) ProtoMessage() {}

func (x *PrescriptionItem) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_prescription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrescriptionItem.ProtoReflect.Descriptor instead.
func (*PrescriptionItem) Descriptor() ([]byte, []int) {
	return file_prescription_prescription_proto_rawDescGZIP(), []int{0}
}

func (x *PrescriptionItem) GetDrugId() int64 {
	if x != nil {
		return x.DrugId
	}
	return 0
}

func (x *PrescriptionItem) GetDrugName() string {
	if x != nil {
		return x.DrugName
	}
	return ""
}

func (x *PrescriptionItem) GetSpecification() string {
	if x != nil {
		return x.Specification
	}
	return ""
}

func (x *PrescriptionItem) GetUsageLabel() string {
	if x != nil {
		return x.UsageLabel
	}
	return ""
}

func (x *PrescriptionItem) GetDosage() string {
	if x != nil {
		return x.Dosage
	}
	return ""
}

func (x *PrescriptionItem) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *PrescriptionItem) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *PrescriptionItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PrescriptionItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 创建处方请求
type CreatePrescriptionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PatientId        int64                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`                     // 患者ID
	EncounterId      int64                  `protobuf:"varint,2,opt,name=encounter_id,json=encounterId,proto3" json:"encounter_id,omitempty"`               // 就诊ID
	PrescriptionType string                 `protobuf:"bytes,3,opt,name=prescription_type,json=prescriptionType,proto3" json:"prescription_type,omitempty"` // 处方类型（西药/中药/检查）
	Items            []*PrescriptionItem    `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`                                               // 处方明细
	Note             string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`                                                 // 备注
	Doctor           *common.UserContext    `protobuf:"bytes,6,opt,name=doctor,proto3" json:"doctor,omitempty"`                                             // 开方医生
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatePrescriptionRequest) Reset() {
	*x = CreatePrescriptionRequest{}
	mi := &file_prescription_prescription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrescriptionRequest) ProtoMessage() {}

func (x *CreatePrescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_prescription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrescriptionRequest.ProtoReflect.Descriptor instead.
func (*CreatePrescriptionRequest) Descriptor() ([]byte, []int) {
	return file_prescription_prescription_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePrescriptionRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *CreatePrescriptionRequest) GetEncounterId() int64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

func (x *CreatePrescriptionRequest) GetPrescriptionType() string {
	if x != nil {
		return x.PrescriptionType
	}
	return ""
}

func (x *CreatePrescriptionRequest) GetItems() []*PrescriptionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreatePrescriptionRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CreatePrescriptionRequest) GetDoctor() *common.UserContext {
	if x != nil {
		return x.Doctor
	}
	return nil
}

// 创建处方响应
type CreatePrescriptionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrescriptionId int64                  `protobuf:"varint,1,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"` // 处方ID
	PrescriptionNo string                 `protobuf:"bytes,2,opt,name=prescription_no,json=prescriptionNo,proto3" json:"prescription_no,omitempty"`  // 处方编号
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                        // 状态
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePrescriptionResponse) Reset() {
	*x = CreatePrescriptionResponse{}
	mi := &file_prescription_prescription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrescriptionResponse) ProtoMessage() {}

func (x *CreatePrescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_prescription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrescriptionResponse.ProtoReflect.Descriptor instead.
func (*CreatePrescriptionResponse) Descriptor() ([]byte, []int) {
	return file_prescription_prescription_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePrescriptionResponse) GetPrescriptionId() int64 {
	if x != nil {
		return x.PrescriptionId
	}
	return 0
}

func (x *CreatePrescriptionResponse) GetPrescriptionNo() string {
	if x != nil {
		return x.PrescriptionNo
	}
	return ""
}

func (x *CreatePrescriptionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 提交审核请求
type SubmitReviewRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrescriptionId int64                  `protobuf:"varint,1,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"` // 处方ID
	Reviewer       *common.UserContext    `protobuf:"bytes,2,opt,name=reviewer,proto3" json:"reviewer,omitempty"`                                    // 审核人
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitReviewRequest) Reset() {
	*x = SubmitReviewRequest{}
	mi := &file_prescription_prescription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReviewRequest) ProtoMessage() {}

func (x *SubmitReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_prescription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReviewRequest.ProtoReflect.Descriptor instead.
func (*SubmitReviewRequest) Descriptor() ([]byte, []int) {
	return file_prescription_prescription_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitReviewRequest) GetPrescriptionId() int64 {
	if x != nil {
		return x.PrescriptionId
	}
	return 0
}

func (x *SubmitReviewRequest) GetReviewer() *common.UserContext {
	if x != nil {
		return x.Reviewer
	}
	return nil
}

// 提交审核响应
type SubmitReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"` // 审核记录ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                      // 审核状态（通过/驳回）
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`                    // 审核意见
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReviewResponse) Reset() {
	*x = SubmitReviewResponse{}
	mi := &file_prescription_prescription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReviewResponse) ProtoMessage() {}

func (x *SubmitReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_prescription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReviewResponse.ProtoReflect.Descriptor instead.
func (*SubmitReviewResponse) Descriptor() ([]byte, []int) {
	return file_prescription_prescription_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitReviewResponse) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *SubmitReviewResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitReviewResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_prescription_prescription_proto protoreflect.FileDescriptor

const file_prescription_prescription_proto_rawDesc = "" +
	"\n" +
	"\x1fprescription/prescription.proto\x12\fprescription\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\x8d\x02\n" +
	"\x10PrescriptionItem\x12\x17\n" +
	"\adrug_id\x18\x01 \x01(\x03R\x06drugId\x12\x1b\n" +
	"\tdrug_name\x18\x02 \x01(\tR\bdrugName\x12$\n" +
	"\rspecification\x18\x03 \x01(\tR\rspecification\x12\x1f\n" +
	"\vusage_label\x18\x04 \x01(\tR\n" +
	"usageLabel\x12\x16\n" +
	"\x06dosage\x18\x05 \x01(\tR\x06dosage\x12\x1c\n" +
	"\tfrequency\x18\x06 \x01(\tR\tfrequency\x12\x12\n" +
	"\x04days\x18\a \x01(\x05R\x04days\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x05R\bquantity\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\"\x81\x02\n" +
	"\x19CreatePrescriptionRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x03R\tpatientId\x12!\n" +
	"\fencounter_id\x18\x02 \x01(\x03R\vencounterId\x12+\n" +
	"\x11prescription_type\x18\x03 \x01(\tR\x10prescriptionType\x124\n" +
	"\x05items\x18\x04 \x03(\v2\x1e.prescription.PrescriptionItemR\x05items\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12+\n" +
	"\x06doctor\x18\x06 \x01(\v2\x13.common.UserContextR\x06doctor\"\x86\x01\n" +
	"\x1aCreatePrescriptionResponse\x12'\n" +
	"\x0fprescription_id\x18\x01 \x01(\x03R\x0eprescriptionId\x12'\n" +
	"\x0fprescription_no\x18\x02 \x01(\tR\x0eprescriptionNo\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"o\n" +
	"\x13SubmitReviewRequest\x12'\n" +
	"\x0fprescription_id\x18\x01 \x01(\x03R\x0eprescriptionId\x12/\n" +
	"\breviewer\x18\x02 \x01(\v2\x13.common.UserContextR\breviewer\"e\n" +
	"\x14SubmitReviewResponse\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x03R\breviewId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment2\xd5\x01\n" +
	"\x13PrescriptionService\x12g\n" +
	"\x12CreatePrescription\x12'.prescription.CreatePrescriptionRequest\x1a(.prescription.CreatePrescriptionResponse\x12U\n" +
	"\fSubmitReview\x12!.prescription.SubmitReviewRequest\x1a\".prescription.SubmitReviewResponseBO\n" +
	"\x1ecom.hismixed.grpc.prescriptionZ-github.com/his-mixed/go/pkg/grpc/prescriptionb\x06proto3"

var (
	file_prescription_prescription_proto_rawDescOnce sync.Once
	file_prescription_prescription_proto_rawDescData []byte
)

func file_prescription_prescription_proto_rawDescGZIP() []byte {
	file_prescription_prescription_proto_rawDescOnce.Do(func() {
		file_prescription_prescription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prescription_prescription_proto_rawDesc), len(file_prescription_prescription_proto_rawDesc)))
	})
	return file_prescription_prescription_proto_rawDescData
}

var file_prescription_prescription_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_prescription_prescription_proto_goTypes = []any{
	(*PrescriptionItem)(nil),           // 0: prescription.PrescriptionItem
	(*CreatePrescriptionRequest)(nil),  // 1: prescription.CreatePrescriptionRequest
	(*CreatePrescriptionResponse)(nil), // 2: prescription.CreatePrescriptionResponse
	(*SubmitReviewRequest)(nil),        // 3: prescription.SubmitReviewRequest
	(*SubmitReviewResponse)(nil),       // 4: prescription.SubmitReviewResponse
	(*common.UserContext)(nil),         // 5: common.UserContext
}
var file_prescription_prescription_proto_depIdxs = []int32{
	0, // 0: prescription.CreatePrescriptionRequest.items:type_name -> prescription.PrescriptionItem
	5, // 1: prescription.CreatePrescriptionRequest.doctor:type_name -> common.UserContext
	5, // 2: prescription.SubmitReviewRequest.reviewer:type_name -> common.UserContext
	1, // 3: prescription.PrescriptionService.CreatePrescription:input_type -> prescription.CreatePrescriptionRequest
	3, // 4: prescription.PrescriptionService.SubmitReview:input_type -> prescription.SubmitReviewRequest
	2, // 5: prescription.PrescriptionService.CreatePrescription:output_type -> prescription.CreatePrescriptionResponse
	4, // 6: prescription.PrescriptionService.SubmitReview:output_type -> prescription.SubmitReviewResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_prescription_prescription_proto_init() }
func file_prescription_prescription_proto_init() {
	if File_prescription_prescription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prescription_prescription_proto_rawDesc), len(file_prescription_prescription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prescription_prescription_proto_goTypes,
		DependencyIndexes: file_prescription_prescription_proto_depIdxs,
		MessageInfos:      file_prescription_prescription_proto_msgTypes,
	}.Build()
	File_prescription_prescription_proto = out.File
	file_prescription_prescription_proto_goTypes = nil
	file_prescription_prescription_proto_depIdxs = nil
}
