// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: examination/examination.proto

package examination

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建报告请求
type CreateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`       // 检查医嘱ID
	PatientId     int64                  `protobuf:"varint,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"` // 患者ID
	ExamType      string                 `protobuf:"bytes,3,opt,name=exam_type,json=examType,proto3" json:"exam_type,omitempty"`     // 检查类型
	BodyPart      string                 `protobuf:"bytes,4,opt,name=body_part,json=bodyPart,proto3" json:"body_part,omitempty"`     // 检查部位
	Findings      string                 `protobuf:"bytes,5,opt,name=findings,proto3" json:"findings,omitempty"`                     // 检查所见
	Impression    string                 `protobuf:"bytes,6,opt,name=impression,proto3" json:"impression,omitempty"`                 // 检查印象/诊断
	Operator      *common.UserContext    `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`                     // 报告医师
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportRequest) Reset() {
	*x = CreateReportRequest{}
	mi := &file_examination_examination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportRequest) ProtoMessage() {}

func (x *CreateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examination_examination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportRequest.ProtoReflect.Descriptor instead.
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return file_examination_examination_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReportRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateReportRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *CreateReportRequest) GetExamType() string {
	if x != nil {
		return x.ExamType
	}
	return ""
}

func (x *CreateReportRequest) GetBodyPart() string {
	if x != nil {
		return x.BodyPart
	}
	return ""
}

func (x *CreateReportRequest) GetFindings() string {
	if x != nil {
		return x.Findings
	}
	return ""
}

func (x *CreateReportRequest) GetImpression() string {
	if x != nil {
		return x.Impression
	}
	return ""
}

func (x *CreateReportRequest) GetOperator() *common.UserContext {
	if x != nil {
		return x.Operator
	}
	return nil
}

// 创建报告响应
type CreateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      int64                  `protobuf:"varint,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"` // 报告ID
	ReportNo      string                 `protobuf:"bytes,2,opt,name=report_no,json=reportNo,proto3" json:"report_no,omitempty"`  // 报告编号
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                      // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportResponse) Reset() {
	*x = CreateReportResponse{}
	mi := &file_examination_examination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportResponse) ProtoMessage() {}

func (x *CreateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examination_examination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportResponse.ProtoReflect.Descriptor instead.
func (*CreateReportResponse) Descriptor() ([]byte, []int) {
	return file_examination_examination_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReportResponse) GetReportId() int64 {
	if x != nil {
		return x.ReportId
	}
	return 0
}

func (x *CreateReportResponse) GetReportNo() string {
	if x != nil {
		return x.ReportNo
	}
	return ""
}

func (x *CreateReportResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 获取报告请求
type GetReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      int64                  `protobuf:"varint,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`    // 报告ID
	PatientId     int64                  `protobuf:"varint,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"` // 患者ID
	OrderId       int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`       // 医嘱ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportRequest) Reset() {
	*x = GetReportRequest{}
	mi := &file_examination_examination_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportRequest) ProtoMessage() {}

func (x *GetReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examination_examination_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportRequest.ProtoReflect.Descriptor instead.
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return file_examination_examination_proto_rawDescGZIP(), []int{2}
}

func (x *GetReportRequest) GetReportId() int64 {
	if x != nil {
		return x.ReportId
	}
	return 0
}

func (x *GetReportRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *GetReportRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// 检查报告详情
type ExaminationReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      int64                  `protobuf:"varint,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`         // 报告ID
	PatientId     int64                  `protobuf:"varint,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`      // 患者ID
	PatientName   string                 `protobuf:"bytes,3,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"` // 患者姓名
	ExamType      string                 `protobuf:"bytes,4,opt,name=exam_type,json=examType,proto3" json:"exam_type,omitempty"`          // 检查类型
	BodyPart      string                 `protobuf:"bytes,5,opt,name=body_part,json=bodyPart,proto3" json:"body_part,omitempty"`          // 检查部位
	Findings      string                 `protobuf:"bytes,6,opt,name=findings,proto3" json:"findings,omitempty"`                          // 检查所见
	Impression    string                 `protobuf:"bytes,7,opt,name=impression,proto3" json:"impression,omitempty"`                      // 检查印象
	Conclusion    string                 `protobuf:"bytes,8,opt,name=conclusion,proto3" json:"conclusion,omitempty"`                      // 结论
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`                              // 状态
	ExamTime      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=exam_time,json=examTime,proto3" json:"exam_time,omitempty"`         // 检查时间
	ReportTime    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=report_time,json=reportTime,proto3" json:"report_time,omitempty"`   // 报告时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExaminationReport) Reset() {
	*x = ExaminationReport{}
	mi := &file_examination_examination_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExaminationReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExaminationReport) ProtoMessage() {}

func (x *ExaminationReport) ProtoReflect() protoreflect.Message {
	mi := &file_examination_examination_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExaminationReport.ProtoReflect.Descriptor instead.
func (*ExaminationReport) Descriptor() ([]byte, []int) {
	return file_examination_examination_proto_rawDescGZIP(), []int{3}
}

func (x *ExaminationReport) GetReportId() int64 {
	if x != nil {
		return x.ReportId
	}
	return 0
}

func (x *ExaminationReport) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *ExaminationReport) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *ExaminationReport) GetExamType() string {
	if x != nil {
		return x.ExamType
	}
	return ""
}

func (x *ExaminationReport) GetBodyPart() string {
	if x != nil {
		return x.BodyPart
	}
	return ""
}

func (x *ExaminationReport) GetFindings() string {
	if x != nil {
		return x.Findings
	}
	return ""
}

func (x *ExaminationReport) GetImpression() string {
	if x != nil {
		return x.Impression
	}
	return ""
}

func (x *ExaminationReport) GetConclusion() string {
	if x != nil {
		return x.Conclusion
	}
	return ""
}

func (x *ExaminationReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExaminationReport) GetExamTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExamTime
	}
	return nil
}

func (x *ExaminationReport) GetReportTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReportTime
	}
	return nil
}

// 获取报告响应
type GetReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *ExaminationReport     `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"` // 报告详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportResponse) Reset() {
	*x = GetReportResponse{}
	mi := &file_examination_examination_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportResponse) ProtoMessage() {}

func (x *GetReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examination_examination_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportResponse.ProtoReflect.Descriptor instead.
func (*GetReportResponse) Descriptor() ([]byte, []int) {
	return file_examination_examination_proto_rawDescGZIP(), []int{4}
}

func (x *GetReportResponse) GetReport() *ExaminationReport {
	if x != nil {
		return x.Report
	}
	return nil
}

var File_examination_examination_proto protoreflect.FileDescriptor

const file_examination_examination_proto_rawDesc = "" +
	"\n" +
	"\x1dexamination/examination.proto\x12\vexamination\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xf6\x01\n" +
	"\x13CreateReportRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\x03R\tpatientId\x12\x1b\n" +
	"\texam_type\x18\x03 \x01(\tR\bexamType\x12\x1b\n" +
	"\tbody_part\x18\x04 \x01(\tR\bbodyPart\x12\x1a\n" +
	"\bfindings\x18\x05 \x01(\tR\bfindings\x12\x1e\n" +
	"\n" +
	"impression\x18\x06 \x01(\tR\n" +
	"impression\x12/\n" +
	"\boperator\x18\a \x01(\v2\x13.common.UserContextR\boperator\"h\n" +
	"\x14CreateReportResponse\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\x03R\breportId\x12\x1b\n" +
	"\treport_no\x18\x02 \x01(\tR\breportNo\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"i\n" +
	"\x10GetReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\x03R\breportId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\x03R\tpatientId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\"\x96\x03\n" +
	"\x11ExaminationReport\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\x03R\breportId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\x03R\tpatientId\x12!\n" +
	"\fpatient_name\x18\x03 \x01(\tR\vpatientName\x12\x1b\n" +
	"\texam_type\x18\x04 \x01(\tR\bexamType\x12\x1b\n" +
	"\tbody_part\x18\x05 \x01(\tR\bbodyPart\x12\x1a\n" +
	"\bfindings\x18\x06 \x01(\tR\bfindings\x12\x1e\n" +
	"\n" +
	"impression\x18\a \x01(\tR\n" +
	"impression\x12\x1e\n" +
	"\n" +
	"conclusion\x18\b \x01(\tR\n" +
	"conclusion\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x127\n" +
	"\texam_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bexamTime\x12;\n" +
	"\vreport_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reportTime\"K\n" +
	"\x11GetReportResponse\x126\n" +
	"\x06report\x18\x01 \x01(\v2\x1e.examination.ExaminationReportR\x06report2\xb5\x01\n" +
	"\x12ExaminationService\x12S\n" +
	"\fCreateReport\x12 .examination.CreateReportRequest\x1a!.examination.CreateReportResponse\x12J\n" +
	"\tGetReport\x12\x1d.examination.GetReportRequest\x1a\x1e.examination.GetReportResponseBM\n" +
	"\x1dcom.hismixed.grpc.examinationZ,github.com/his-mixed/go/pkg/grpc/examinationb\x06proto3"

var (
	file_examination_examination_proto_rawDescOnce sync.Once
	file_examination_examination_proto_rawDescData []byte
)

func file_examination_examination_proto_rawDescGZIP() []byte {
	file_examination_examination_proto_rawDescOnce.Do(func() {
		file_examination_examination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examination_examination_proto_rawDesc), len(file_examination_examination_proto_rawDesc)))
	})
	return file_examination_examination_proto_rawDescData
}

var file_examination_examination_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_examination_examination_proto_goTypes = []any{
	(*CreateReportRequest)(nil),   // 0: examination.CreateReportRequest
	(*CreateReportResponse)(nil),  // 1: examination.CreateReportResponse
	(*GetReportRequest)(nil),      // 2: examination.GetReportRequest
	(*ExaminationReport)(nil),     // 3: examination.ExaminationReport
	(*GetReportResponse)(nil),     // 4: examination.GetReportResponse
	(*common.UserContext)(nil),    // 5: common.UserContext
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_examination_examination_proto_depIdxs = []int32{
	5, // 0: examination.CreateReportRequest.operator:type_name -> common.UserContext
	6, // 1: examination.ExaminationReport.exam_time:type_name -> google.protobuf.Timestamp
	6, // 2: examination.ExaminationReport.report_time:type_name -> google.protobuf.Timestamp
	3, // 3: examination.GetReportResponse.report:type_name -> examination.ExaminationReport
	0, // 4: examination.ExaminationService.CreateReport:input_type -> examination.CreateReportRequest
	2, // 5: examination.ExaminationService.GetReport:input_type -> examination.GetReportRequest
	1, // 6: examination.ExaminationService.CreateReport:output_type -> examination.CreateReportResponse
	4, // 7: examination.ExaminationService.GetReport:output_type -> examination.GetReportResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_examination_examination_proto_init() }
func file_examination_examination_proto_init() {
	if File_examination_examination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examination_examination_proto_rawDesc), len(file_examination_examination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examination_examination_proto_goTypes,
		DependencyIndexes: file_examination_examination_proto_depIdxs,
		MessageInfos:      file_examination_examination_proto_msgTypes,
	}.Build()
	File_examination_examination_proto = out.File
	file_examination_examination_proto_goTypes = nil
	file_examination_examination_proto_depIdxs = nil
}
