// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: inpatient/inpatient.proto

package inpatient

import (
	common "github.com/his-mixed/go/pkg/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 入院请求
type AdmitPatientRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PatientId          int64                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`                           // 患者ID
	AdmissionDeptId    int64                  `protobuf:"varint,2,opt,name=admission_dept_id,json=admissionDeptId,proto3" json:"admission_dept_id,omitempty"`       // 入院科室ID
	WardId             int64                  `protobuf:"varint,3,opt,name=ward_id,json=wardId,proto3" json:"ward_id,omitempty"`                                    // 病区ID
	BedNo              string                 `protobuf:"bytes,4,opt,name=bed_no,json=bedNo,proto3" json:"bed_no,omitempty"`                                        // 床位号
	AdmissionDiagnosis string                 `protobuf:"bytes,5,opt,name=admission_diagnosis,json=admissionDiagnosis,proto3" json:"admission_diagnosis,omitempty"` // 入院诊断
	AdmissionType      string                 `protobuf:"bytes,6,opt,name=admission_type,json=admissionType,proto3" json:"admission_type,omitempty"`                // 入院方式（门诊/急诊/转院）
	ConditionLevel     string                 `protobuf:"bytes,7,opt,name=condition_level,json=conditionLevel,proto3" json:"condition_level,omitempty"`             // 病情等级
	Operator           *common.UserContext    `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`                                               // 操作人
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AdmitPatientRequest) Reset() {
	*x = AdmitPatientRequest{}
	mi := &file_inpatient_inpatient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitPatientRequest) ProtoMessage() {}

func (x *AdmitPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inpatient_inpatient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitPatientRequest.ProtoReflect.Descriptor instead.
func (*AdmitPatientRequest) Descriptor() ([]byte, []int) {
	return file_inpatient_inpatient_proto_rawDescGZIP(), []int{0}
}

func (x *AdmitPatientRequest) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *AdmitPatientRequest) GetAdmissionDeptId() int64 {
	if x != nil {
		return x.AdmissionDeptId
	}
	return 0
}

func (x *AdmitPatientRequest) GetWardId() int64 {
	if x != nil {
		return x.WardId
	}
	return 0
}

func (x *AdmitPatientRequest) GetBedNo() string {
	if x != nil {
		return x.BedNo
	}
	return ""
}

func (x *AdmitPatientRequest) GetAdmissionDiagnosis() string {
	if x != nil {
		return x.AdmissionDiagnosis
	}
	return ""
}

func (x *AdmitPatientRequest) GetAdmissionType() string {
	if x != nil {
		return x.AdmissionType
	}
	return ""
}

func (x *AdmitPatientRequest) GetConditionLevel() string {
	if x != nil {
		return x.ConditionLevel
	}
	return ""
}

func (x *AdmitPatientRequest) GetOperator() *common.UserContext {
	if x != nil {
		return x.Operator
	}
	return nil
}

// 入院响应
type AdmitPatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InpatientId   int64                  `protobuf:"varint,1,opt,name=inpatient_id,json=inpatientId,proto3" json:"inpatient_id,omitempty"` // 住院号
	AdmissionNo   string                 `protobuf:"bytes,2,opt,name=admission_no,json=admissionNo,proto3" json:"admission_no,omitempty"`  // 入院编号
	WardName      string                 `protobuf:"bytes,3,opt,name=ward_name,json=wardName,proto3" json:"ward_name,omitempty"`           // 病区名称
	BedNo         string                 `protobuf:"bytes,4,opt,name=bed_no,json=bedNo,proto3" json:"bed_no,omitempty"`                    // 床位号
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                               // 状态
	AdmittedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=admitted_at,json=admittedAt,proto3" json:"admitted_at,omitempty"`     // 入院时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitPatientResponse) Reset() {
	*x = AdmitPatientResponse{}
	mi := &file_inpatient_inpatient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitPatientResponse) ProtoMessage() {}

func (x *AdmitPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inpatient_inpatient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitPatientResponse.ProtoReflect.Descriptor instead.
func (*AdmitPatientResponse) Descriptor() ([]byte, []int) {
	return file_inpatient_inpatient_proto_rawDescGZIP(), []int{1}
}

func (x *AdmitPatientResponse) GetInpatientId() int64 {
	if x != nil {
		return x.InpatientId
	}
	return 0
}

func (x *AdmitPatientResponse) GetAdmissionNo() string {
	if x != nil {
		return x.AdmissionNo
	}
	return ""
}

func (x *AdmitPatientResponse) GetWardName() string {
	if x != nil {
		return x.WardName
	}
	return ""
}

func (x *AdmitPatientResponse) GetBedNo() string {
	if x != nil {
		return x.BedNo
	}
	return ""
}

func (x *AdmitPatientResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdmitPatientResponse) GetAdmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AdmittedAt
	}
	return nil
}

// 出院请求
type DischargePatientRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InpatientId        int64                  `protobuf:"varint,1,opt,name=inpatient_id,json=inpatientId,proto3" json:"inpatient_id,omitempty"`                     // 住院号
	DischargeType      string                 `protobuf:"bytes,2,opt,name=discharge_type,json=dischargeType,proto3" json:"discharge_type,omitempty"`                // 出院方式（治愈/好转/转院/死亡）
	DischargeDiagnosis string                 `protobuf:"bytes,3,opt,name=discharge_diagnosis,json=dischargeDiagnosis,proto3" json:"discharge_diagnosis,omitempty"` // 出院诊断
	Summary            string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`                                                 // 出院小结
	Operator           *common.UserContext    `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`                                               // 操作人
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DischargePatientRequest) Reset() {
	*x = DischargePatientRequest{}
	mi := &file_inpatient_inpatient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DischargePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DischargePatientRequest) ProtoMessage() {}

func (x *DischargePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inpatient_inpatient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DischargePatientRequest.ProtoReflect.Descriptor instead.
func (*DischargePatientRequest) Descriptor() ([]byte, []int) {
	return file_inpatient_inpatient_proto_rawDescGZIP(), []int{2}
}

func (x *DischargePatientRequest) GetInpatientId() int64 {
	if x != nil {
		return x.InpatientId
	}
	return 0
}

func (x *DischargePatientRequest) GetDischargeType() string {
	if x != nil {
		return x.DischargeType
	}
	return ""
}

func (x *DischargePatientRequest) GetDischargeDiagnosis() string {
	if x != nil {
		return x.DischargeDiagnosis
	}
	return ""
}

func (x *DischargePatientRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *DischargePatientRequest) GetOperator() *common.UserContext {
	if x != nil {
		return x.Operator
	}
	return nil
}

// 出院响应
type DischargePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InpatientId   int64                  `protobuf:"varint,1,opt,name=inpatient_id,json=inpatientId,proto3" json:"inpatient_id,omitempty"`   // 住院号
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                 // 状态
	DischargedAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=discharged_at,json=dischargedAt,proto3" json:"discharged_at,omitempty"` // 出院时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DischargePatientResponse) Reset() {
	*x = DischargePatientResponse{}
	mi := &file_inpatient_inpatient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DischargePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DischargePatientResponse) ProtoMessage() {}

func (x *DischargePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inpatient_inpatient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DischargePatientResponse.ProtoReflect.Descriptor instead.
func (*DischargePatientResponse) Descriptor() ([]byte, []int) {
	return file_inpatient_inpatient_proto_rawDescGZIP(), []int{3}
}

func (x *DischargePatientResponse) GetInpatientId() int64 {
	if x != nil {
		return x.InpatientId
	}
	return 0
}

func (x *DischargePatientResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DischargePatientResponse) GetDischargedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DischargedAt
	}
	return nil
}

var File_inpatient_inpatient_proto protoreflect.FileDescriptor

const file_inpatient_inpatient_proto_rawDesc = "" +
	"\n" +
	"\x19inpatient/inpatient.proto\x12\tinpatient\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xc2\x02\n" +
	"\x13AdmitPatientRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x03R\tpatientId\x12*\n" +
	"\x11admission_dept_id\x18\x02 \x01(\x03R\x0fadmissionDeptId\x12\x17\n" +
	"\award_id\x18\x03 \x01(\x03R\x06wardId\x12\x15\n" +
	"\x06bed_no\x18\x04 \x01(\tR\x05bedNo\x12/\n" +
	"\x13admission_diagnosis\x18\x05 \x01(\tR\x12admissionDiagnosis\x12%\n" +
	"\x0eadmission_type\x18\x06 \x01(\tR\radmissionType\x12'\n" +
	"\x0fcondition_level\x18\a \x01(\tR\x0econditionLevel\x12/\n" +
	"\boperator\x18\b \x01(\v2\x13.common.UserContextR\boperator\"\xe5\x01\n" +
	"\x14AdmitPatientResponse\x12!\n" +
	"\finpatient_id\x18\x01 \x01(\x03R\vinpatientId\x12!\n" +
	"\fadmission_no\x18\x02 \x01(\tR\vadmissionNo\x12\x1b\n" +
	"\tward_name\x18\x03 \x01(\tR\bwardName\x12\x15\n" +
	"\x06bed_no\x18\x04 \x01(\tR\x05bedNo\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12;\n" +
	"\vadmitted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"admittedAt\"\xdf\x01\n" +
	"\x17DischargePatientRequest\x12!\n" +
	"\finpatient_id\x18\x01 \x01(\x03R\vinpatientId\x12%\n" +
	"\x0edischarge_type\x18\x02 \x01(\tR\rdischargeType\x12/\n" +
	"\x13discharge_diagnosis\x18\x03 \x01(\tR\x12dischargeDiagnosis\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12/\n" +
	"\boperator\x18\x05 \x01(\v2\x13.common.UserContextR\boperator\"\x96\x01\n" +
	"\x18DischargePatientResponse\x12!\n" +
	"\finpatient_id\x18\x01 \x01(\x03R\vinpatientId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12?\n" +
	"\rdischarged_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fdischargedAt2\xc0\x01\n" +
	"\x10InpatientService\x12O\n" +
	"\fAdmitPatient\x12\x1e.inpatient.AdmitPatientRequest\x1a\x1f.inpatient.AdmitPatientResponse\x12[\n" +
	"\x10DischargePatient\x12\".inpatient.DischargePatientRequest\x1a#.inpatient.DischargePatientResponseBI\n" +
	"\x1bcom.hismixed.grpc.inpatientZ*github.com/his-mixed/go/pkg/grpc/inpatientb\x06proto3"

var (
	file_inpatient_inpatient_proto_rawDescOnce sync.Once
	file_inpatient_inpatient_proto_rawDescData []byte
)

func file_inpatient_inpatient_proto_rawDescGZIP() []byte {
	file_inpatient_inpatient_proto_rawDescOnce.Do(func() {
		file_inpatient_inpatient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inpatient_inpatient_proto_rawDesc), len(file_inpatient_inpatient_proto_rawDesc)))
	})
	return file_inpatient_inpatient_proto_rawDescData
}

var file_inpatient_inpatient_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_inpatient_inpatient_proto_goTypes = []any{
	(*AdmitPatientRequest)(nil),      // 0: inpatient.AdmitPatientRequest
	(*AdmitPatientResponse)(nil),     // 1: inpatient.AdmitPatientResponse
	(*DischargePatientRequest)(nil),  // 2: inpatient.DischargePatientRequest
	(*DischargePatientResponse)(nil), // 3: inpatient.DischargePatientResponse
	(*common.UserContext)(nil),       // 4: common.UserContext
	(*timestamppb.Timestamp)(nil),    // 5: google.protobuf.Timestamp
}
var file_inpatient_inpatient_proto_depIdxs = []int32{
	4, // 0: inpatient.AdmitPatientRequest.operator:type_name -> common.UserContext
	5, // 1: inpatient.AdmitPatientResponse.admitted_at:type_name -> google.protobuf.Timestamp
	4, // 2: inpatient.DischargePatientRequest.operator:type_name -> common.UserContext
	5, // 3: inpatient.DischargePatientResponse.discharged_at:type_name -> google.protobuf.Timestamp
	0, // 4: inpatient.InpatientService.AdmitPatient:input_type -> inpatient.AdmitPatientRequest
	2, // 5: inpatient.InpatientService.DischargePatient:input_type -> inpatient.DischargePatientRequest
	1, // 6: inpatient.InpatientService.AdmitPatient:output_type -> inpatient.AdmitPatientResponse
	3, // 7: inpatient.InpatientService.DischargePatient:output_type -> inpatient.DischargePatientResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_inpatient_inpatient_proto_init() }
func file_inpatient_inpatient_proto_init() {
	if File_inpatient_inpatient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inpatient_inpatient_proto_rawDesc), len(file_inpatient_inpatient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inpatient_inpatient_proto_goTypes,
		DependencyIndexes: file_inpatient_inpatient_proto_depIdxs,
		MessageInfos:      file_inpatient_inpatient_proto_msgTypes,
	}.Build()
	File_inpatient_inpatient_proto = out.File
	file_inpatient_inpatient_proto_goTypes = nil
	file_inpatient_inpatient_proto_depIdxs = nil
}
