// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: inpatient/inpatient.proto

package inpatient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InpatientService_AdmitPatient_FullMethodName     = "/inpatient.InpatientService/AdmitPatient"
	InpatientService_DischargePatient_FullMethodName = "/inpatient.InpatientService/DischargePatient"
)

// InpatientServiceClient is the client API for InpatientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 住院服务
type InpatientServiceClient interface {
	// 办理入院
	AdmitPatient(ctx context.Context, in *AdmitPatientRequest, opts ...grpc.CallOption) (*AdmitPatientResponse, error)
	// 办理出院
	DischargePatient(ctx context.Context, in *DischargePatientRequest, opts ...grpc.CallOption) (*DischargePatientResponse, error)
}

type inpatientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInpatientServiceClient(cc grpc.ClientConnInterface) InpatientServiceClient {
	return &inpatientServiceClient{cc}
}

func (c *inpatientServiceClient) AdmitPatient(ctx context.Context, in *AdmitPatientRequest, opts ...grpc.CallOption) (*AdmitPatientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdmitPatientResponse)
	err := c.cc.Invoke(ctx, InpatientService_AdmitPatient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inpatientServiceClient) DischargePatient(ctx context.Context, in *DischargePatientRequest, opts ...grpc.CallOption) (*DischargePatientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DischargePatientResponse)
	err := c.cc.Invoke(ctx, InpatientService_DischargePatient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InpatientServiceServer is the server API for InpatientService service.
// All implementations must embed UnimplementedInpatientServiceServer
// for forward compatibility.
//
// 住院服务
type InpatientServiceServer interface {
	// 办理入院
	AdmitPatient(context.Context, *AdmitPatientRequest) (*AdmitPatientResponse, error)
	// 办理出院
	DischargePatient(context.Context, *DischargePatientRequest) (*DischargePatientResponse, error)
	mustEmbedUnimplementedInpatientServiceServer()
}

// UnimplementedInpatientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInpatientServiceServer struct{}

func (UnimplementedInpatientServiceServer) AdmitPatient(context.Context, *AdmitPatientRequest) (*AdmitPatientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdmitPatient not implemented")
}
func (UnimplementedInpatientServiceServer) DischargePatient(context.Context, *DischargePatientRequest) (*DischargePatientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DischargePatient not implemented")
}
func (UnimplementedInpatientServiceServer) mustEmbedUnimplementedInpatientServiceServer() {}
func (UnimplementedInpatientServiceServer) testEmbeddedByValue()                          {}

// UnsafeInpatientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InpatientServiceServer will
// result in compilation errors.
type UnsafeInpatientServiceServer interface {
	mustEmbedUnimplementedInpatientServiceServer()
}

func RegisterInpatientServiceServer(s grpc.ServiceRegistrar, srv InpatientServiceServer) {
	// If the following call panics, it indicates UnimplementedInpatientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InpatientService_ServiceDesc, srv)
}

func _InpatientService_AdmitPatient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdmitPatientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InpatientServiceServer).AdmitPatient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InpatientService_AdmitPatient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InpatientServiceServer).AdmitPatient(ctx, req.(*AdmitPatientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InpatientService_DischargePatient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DischargePatientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InpatientServiceServer).DischargePatient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InpatientService_DischargePatient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InpatientServiceServer).DischargePatient(ctx, req.(*DischargePatientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InpatientService_ServiceDesc is the grpc.ServiceDesc for InpatientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InpatientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inpatient.InpatientService",
	HandlerType: (*InpatientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdmitPatient",
			Handler:    _InpatientService_AdmitPatient_Handler,
		},
		{
			MethodName: "DischargePatient",
			Handler:    _InpatientService_DischargePatient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inpatient/inpatient.proto",
}
